IMPORTS

In [317]:
import pandas as pd
import numpy as np
import json
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
import ast

In [318]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

LOAD DATA

In [319]:
# Import Raw tables and save in variables
CM_customers_raw         = Path("../data/INPUT/chartmogul_customers/raw/chartmogul_customers_raw.json")
CM_metrics_raw           = Path("../data/INPUT/chartmogul_metrics/raw/chartmogul_metrics_raw.json")
CM_mrr_components_raw    = Path("../data/INPUT/chartmogul_mrr_components/raw/chartmogul_mrr_components_raw.json")
CM_plans_raw             = Path("../data/INPUT/chartmogul_plans/raw/chartmogul_plans_raw.json")
HD_contacts_raw          = Path("../data/INPUT/holded_contacts/raw/holded_contacts_raw.json")
HD_expenses_raw          = Path("../data/INPUT/holded_expenses/raw/holded_expenses_raw.json")
HD_invoices_raw          = Path("../data/INPUT/holded_invoices/raw/holded_invoices_raw.json")
HD_payments_raw          = Path("../data/INPUT/holded_payments/raw/holded_payments_raw.json")
HD_purchases_raw         = Path("../data/INPUT/holded_purchases/raw/holded_purchases_raw.json")

In [320]:
# Import Clean tables and save in variables
CM_customers_clean =            "../data/INPUT/chartmogul_customers/clean/chartmogul_customers_clean.csv"
CM_metrics_clean =              "../data/INPUT/chartmogul_metrics/clean/chartmogul_metrics_clean.csv"
CM_mrr_components_clean =       "../data/INPUT/chartmogul_mrr_components/clean/chartmogul_mrr_components_clean.csv"
CM_plans_clean =                "../data/INPUT/chartmogul_plans/clean/chartmogul_plans_clean.csv"
HD_contacts_clean =             "../data/INPUT/holded_contacts/clean/holded_contacts_clean.csv"
HD_expenses_clean =             "../data/INPUT/holded_expenses/clean/holded_expenses_clean.csv"
HD_invoices_clean =             "../data/INPUT/holded_invoices/clean/holded_invoices_clean.csv"
HD_payments_clean =             "../data/INPUT/holded_payments/clean/holded_payments_clean.csv"
HD_purchases_clean =            "../data/INPUT/holded_purchases/clean/holded_purchases_clean.csv"
HD_cuadro_cuentas =             "../data/INPUT/holded_cuadro_de_cuentas.csv"
HD_contacts_lookup =            "../data/INPUT/holded_contacts_lookup.csv"

In [321]:
# Create Raw Table Dataframes
df_CM_customers_raw =           pd.read_json(CM_customers_raw)
df_CM_metrics_raw =             pd.read_json(CM_metrics_raw)
df_CM_mrr_components_raw =      pd.read_json(CM_mrr_components_raw)
df_CM_plans_raw =               pd.read_json(CM_plans_raw)
df_HD_contacts_raw =            pd.read_json(HD_contacts_raw)
df_HD_expenses_raw =            pd.read_json(HD_expenses_raw)
df_HD_invoices_raw =            pd.read_json(HD_invoices_raw)
df_HD_payments_raw =            pd.read_json(HD_payments_raw)
df_HD_purchases_raw =           pd.read_json(HD_purchases_raw)

In [322]:
# Create Clean Table Dataframes
df_CM_customers_clean =           pd.read_csv(CM_customers_clean)
df_CM_metrics_clean =             pd.read_csv(CM_metrics_clean)
df_CM_mrr_components_clean =      pd.read_csv(CM_mrr_components_clean)
df_CM_plans_clean =               pd.read_csv(CM_plans_clean)
df_HD_contacts_clean =            pd.read_csv(HD_contacts_clean)
df_HD_expenses_clean =            pd.read_csv(HD_expenses_clean)
df_HD_invoices_clean =            pd.read_csv(HD_invoices_clean)
df_HD_payments_clean =            pd.read_csv(HD_payments_clean)
df_HD_purchases_clean =           pd.read_csv(HD_purchases_clean)
df_HD_cuadro_cuentas =            pd.read_csv(HD_cuadro_cuentas)
df_HD_contacts_lookup =           pd.read_csv(HD_contacts_lookup)

In [323]:
# Create dictionary of all tables 
all_tables_clean_dict = {
    'df_CM_customers_clean': df_CM_customers_clean,
    'df_CM_metrics_clean': df_CM_metrics_clean,
    'df_CM_mrr_components_clean': df_CM_mrr_components_clean,
    'df_CM_plans_clean': df_CM_plans_clean,
    'df_HD_contacts_clean': df_HD_contacts_clean,
    'df_HD_expenses_clean': df_HD_expenses_clean,
    'df_HD_invoices_clean': df_HD_invoices_clean,
    'df_HD_payments_clean': df_HD_payments_clean,
    'df_HD_purchases_clean': df_HD_purchases_clean
}

FUNCTION: GET TOP 3 VALUES

In [324]:
# Define function that outputs top 3 values for each column in each table 
def get_top_3_values(dfs_dict):
    top_values = {}

    for name, df in dfs_dict.items():
        print(f"\n=== {name} ===")
        for col in df.columns:
            top_vals = df[col].value_counts(dropna=False).head(3).index.tolist()
            top_values[(name, col)] = top_vals
            print(f"{col}: {top_vals}")

    return top_values

In [325]:
# Call top 3 values function, passing dictionary of tables as argument
top_3 = get_top_3_values(all_tables_clean_dict)

=== df_CM_customers_clean ===
id: [177867729, 177867728, 177867721]
uuid: ['cus_9a55ecba-bcdc-4d19-89d1-05ddfac08906', 'cus_60c6c415-10dd-485f-ad9c-60708596de49', 'cus_514e79e5-a727-48cb-96ad-daa56f6aca0b']
external_id: ['cus_PubGEWYD0zJS7r', 'cus_Pw72IlNTuidXmn', 'cus_PzNLrP3gZiXUek']
name: ['Gemma Voces Pons', 'Antonio Manuel Espín Martín', 'Edicom Capital']
email: [nan, 'lgalceran@edicom.es', 'carla.fernandez@emburse.com']
status: ['Active', 'New Lead', 'Cancelled']
customer-since: [nan, '2024-04-12T15:30:48+00:00', '2024-04-16T16:24:29+00:00']
data_source_uuid: ['ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c', 'ds_78983044-48ff-11ef-a3c9-aba08b7ca782']
data_source_uuids: ["['ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c']", "['ds_78983044-48ff-11ef-a3c9-aba08b7ca782']", "['ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c', 'ds_78983044-48ff-11ef-a3c9-aba08b7ca782']"]
external_ids: ["['cus_PubGEWYD0zJS7r']", "['6946177521', 'cus_Pw72IlNTuidXmn']", "['9678837704', '31471805157', 'cus_PzNLrP3gZiXUek']"]
company: [nan, 'KOMBO IA - Invoice ', 'Daniel Terrasa Martinez']
country: ['ES', nan, 'US']
state: [nan, 'CA', 'FL']
city: [nan, 'Barcelona', 'Madrid']
zip: [nan, '28006', '08004']
lead_created_at: [nan, '2025-06-06 10:39:41.253000+00:00', '2025-01-21 10:58:35.018000+00:00']
free_trial_started_at: [nan, '2025-05-07T12:06:17.000Z', '2025-04-04T09:41:55.000Z']
mrr: [0, 4900, 9900]
arr: [0, 58800, 118800]
billing-system-url: ['https://dashboard.stripe.com/customers/cus_PubGEWYD0zJS7r', 'https://dashboard.stripe.com/customers/cus_Pw72IlNTuidXmn', 'https://dashboard.stripe.com/customers/cus_PzNLrP3gZiXUek']
chartmogul-url: ['https://app.chartmogul.com/#/customers/177867729-Edicom_Capital', 'https://app.chartmogul.com/#/customers/177867728-Antonio_Manuel_Espn_Martn', 'https://app.chartmogul.com/#/customers/177867721-Carla_Kessler']
billing-system-type: ['HubSpot', 'Stripe']
currency: ['EUR']
currency-sign: ['€']
owner: [nan]
website_url: [nan, 'https://hanbai.io', 'https://getkombo.ai']
attributes.tags: ['[]', "['merged-customer']", "['merged-customer', 'merged-customer']"]
address.country: ['Spain', nan, 'United States']
address.state: [nan, 'California', 'Florida']
address.city: [nan, 'Barcelona', 'Madrid']
address.address_zip: [nan, '28006', '08004']
attributes.hubspot.Company_owner: [nan, 1395565787.0, 1777132963.0]
attributes.hubspot.Lifecycle_Stage: [nan, 'opportunity', 'lead']
attributes.hubspot.Latest_Source: [nan, 'OFFLINE']
attributes.hubspot.Original_Source: [nan, 'OFFLINE']
attributes.stripe.userId: [nan, '23qKJB7vMwNvTsflT6jA37zVgyh2', '8NRp4H64iDfzoGDPbyU34KrqIRi1']
attributes.stripe.companyId: [nan, 'd4jm75zwsjphfue3xnnf00y9', 'brpx4p8tro9b1nzljlgb456p']
attributes.hubspot.Industry: [nan, 'COMPUTER_SOFTWARE', 'LEISURE_TRAVEL_TOURISM']
attributes.hubspot.Time_Last_Seen: [nan, '2025-01-28T11:11:00Z', '2025-01-09T10:20:00Z']
attributes.hubspot.Type: [nan, 'PROSPECT', 'RESELLER']

=== df_CM_metrics_clean ===
date: ['2024-03-31', '2024-04-30', '2024-05-31']
mrr: [0, 27900, 56400]
mrr-percentage-change: [0.0]
arr: [0, 334800, 676800]
arr-percentage-change: [0.0]
customer-churn-rate: [0.0, 15.38, 6.25]
customer-churn-rate-percentage-change: [0.0]
mrr-churn-rate: [0.0, -17.56, 12.23]
mrr-churn-rate-percentage-change: [0.0]
ltv: [0, 391757, 323789]
ltv-percentage-change: [0.0]
customers: [16, 38, 6]
customers-percentage-change: [0.0]
asp: [0, 4650, 5900]
asp-percentage-change: [0.0]
arpa: [0, 4650, 5640]
arpa-percentage-change: [0.0]
year: [2024, 2025]
month: [3, 4, 5]
month_start: ['2024-03-01', '2024-04-01', '2024-05-01']

=== df_CM_mrr_components_clean ===
date: ['2024-03-31', '2024-04-30', '2024-05-31']
mrr: [0, 27900, 56400]
percentage-change: [0.0]
mrr-new-business: [0, 27900, 23600]
mrr-expansion: [0, 4900, 12793]
mrr-contraction: [0, -6900, -1544]
mrr-churn: [0, -3500, -2500]
mrr-reactivation: [0, 5800, 60360]

=== df_CM_plans_clean ===
external_id: ['price_1RoS8dRoTYKnwsE7M1zk0IKJ', 'price_1RoQ1qRoTYKnwsE7tfavz9eF', 'price_1RbiNiRoTYKnwsE7H03OCv8j']
name: ['SILVER PLAN', 'CORE PLAN', 'PLATINUM PLAN']
interval_count: [1, 3]
uuid: ['pl_e5ad8512-3271-40a0-be83-86d809633a4e', 'pl_30756617-8498-4c25-b82c-97bd8a108520', 'pl_fd519fda-d574-4cd4-939c-c40f8543ba8c']
interval_unit: ['month', 'year']
data_source_uuid: ['ds_78983044-48ff-11ef-a3c9-aba08b7ca782']

=== df_HD_contacts_clean ===
id: ['6694f45fc6f6db032502c35b', '6694f5a3919746067d00ab14', '6694f65bad0998298507286e']
customId: [nan, 5863352.0, 5971454.0]
name: [nan, 'Weekendesk', 'Miriam Piriam']
code: [nan, 'NOCIF', 'B60036787']
vatnumber: [nan, 'NOCIF', 'B60036787']
tradeName: [nan, 'CEASA ASESORES FISCALES, S.L.', 'REGISTRE MERCANTIL DE BARCELONA']
email: [nan, 'admin@factoriaf5.org', 'administracion@nuclio.school']
mobile: [nan]
phone: [nan, '+34646660186', '+4971112356333']
type: [nan, 'supplier', 'client']
iban: [nan]
swift: [nan]
groupId: [nan]
clientRecord: ['0', '{"num": 43000499, "name": "Onegolive Services S.L."}', '{"num": 43000006, "name": "Asociaci\\u00f3n Factor\\u00eda F5"}']
supplierRecord: ['0', '{"num": 41000002, "name": "CEASA ASESORES FISCALES, S.L."}', '{"num": 41000008, "name": "REGISTRE MERCANTIL DE BARCELONA"}']
billAddress: ['{"address": null, "city": null, "postalCode": "", "province": null, "country": null, "countryCode": null, "info": ""}', '{"address": null, "city": null, "postalCode": "", "province": null, "country": "Espa\\u00f1a", "countryCode": "ES", "info": ""}', '{"address": null, "city": null, "postalCode": "", "province": null, "country": "Estados Unidos", "countryCode": "US", "info": ""}']
customFields: ['[]']
defaults: ['{"salesChannel": 0, "expensesAccount": 0, "dueDays": 0, "paymentDay": 0, "paymentMethod": 0, "discount": 0, "language": "es", "currency": null, "salesTax": [], "purchasesTax": [], "accumulateInForm347": "yes"}', '{"salesChannel": 0, "expensesAccount": 0, "dueDays": 0, "paymentDay": 0, "paymentMethod": 0, "discount": 0, "language": "es", "currency": "eur", "salesTax": [], "purchasesTax": [], "accumulateInForm347": "yes"}', '{"salesChannel": 0, "expensesAccount": 0, "dueDays": 0, "paymentDay": 0, "paymentMethod": 0, "discount": 0, "language": "es", "currency": "eur", "salesTax": [], "purchasesTax": [], "accumulateInForm347": "no"}']
socialNetworks: ['[]', '{"website": ""}', '{"website": "", "facebook": "", "twitter": ""}']
tags: ['[]', '["cogs", "tech", "tool"]', '["opex", "leg", "vendor"]']
notes: ['[]']
contactPersons: ['[]', '[{"personId": "6852bf0dd7f7b87ec2042a0f", "name": "agomez@eragroup.com", "job": "", "phone": "", "email": "agomez@eragroup.com", "sendDocuments": 0}]', '[{"personId": "6852bf0dd7f7b87ec2042a10", "name": "agomez@eragroup.com", "job": "", "phone": "", "email": "", "sendDocuments": 0}]']
shippingAddresses: ['[]']
isperson: [0, 1]
createdAt: [1743522747, 1743522748, 1728465965]
updatedAt: [1752252967, 1752252968, 1752252966]
updatedHash: ['3704e8a63e113125690c97079e41acc8', 'ab20084169517a61d10fde8c4a714d61', '84458d9fbef91d902eac4037bb1b277b']

=== df_HD_expenses_clean ===
id: ['669fbd0a334dc06d2b014bf9', '68680595b0333b5f71004617', '669e994937430c98a60d9470']
name: [' Diferencias negativas de cambio', ' Intereses de deudas con entidades de crédito', ' Otros gastos financieros']
color: ['#c9ec24', '#737472', '#fadd07']
accountNum: [66800000, 66230000, 66900000]

=== df_HD_invoices_clean ===
id: ['68640b2e4d4b9230af022ea8', '68640b2e4d4b9230af022eb5', '68640b2e4d4b9230af022ec5']
contact: ['669a98144faadb9e99042ba1', '66bf5ef731a8f1044a0b869b', '67911f90a1b85762aa0fa323']
contactName: ['Clientes Stripe', 'Fever Labs Inc', 'SPALOPIA SL']
desc: [nan, 'Fever Labs Inc', 'Estefania Tello']
date: ['2024-10-08 22:00:00', '2024-11-08 23:00:00', '2024-11-13 23:00:00']
dueDate: [nan, 1733785200.0, 1733958000.0]
multipledueDate: ['[]', nan]
forecastDate: [nan]
notes: [nan]
tags: ['[]']
products: ["[{'name': '', 'desc': '', 'price': 0, 'units': 1, 'projectid': None, 'tax': 0, 'taxes': [], 'tags': [], 'discount': 0, 'retention': 0, 'weight': 0, 'costPrice': 0, 'sku': 0, 'account': '668572ba1ef7394b7a07f1e5'}]", "[{'name': 'LITE - FREE PLAN', 'desc': '', 'price': 0, 'units': 1, 'projectid': None, 'tax': 0, 'taxes': [], 'tags': [], 'discount': 0, 'retention': 0, 'weight': 0, 'costPrice': 0, 'sku': 0, 'account': '668572ba1ef7394b7a07f1e5'}]", "[{'name': '', 'desc': '', 'price': 49, 'units': 1, 'projectid': None, 'tax': 21, 'taxes': ['s_iva_21'], 'tags': [], 'discount': 0, 'retention': 0, 'weight': 0, 'costPrice': 0, 'sku': 0, 'account': '668572ba1ef7394b7a07f1e5'}]"]
tax: [0.0, 10.29, 4.22]
subtotal: [0.0, 49.0, 20.09]
discount: [0.0, 59.1836735, 20.4081633]
total: [0.0, 59.29, 24.31]
language: ['es']
status: [1, 2]
customFields: ['[]']
docNumber: ['F250383', 'F250384', 'F250385']
currency: ['eur']
currencyChange: [1]
paymentsDetail: [nan, "[{'id': '6864fa85ba573f3f0e088f2c', 'amount': 90.15, 'date': 1751285513, 'bankId': '6697f010aa923f537703964e'}]", "[{'id': '6864fa822531707a9909d4f3', 'amount': 868.67, 'date': 1751290983, 'bankId': '6697f010aa923f537703964e'}]"]
paymentsTotal: [0.0, 59.29, 24.31]
paymentsPending: [0.0, -1.4210854715202004e-14, 2.8421709430404014e-14]
paymentsRefunds: [0.0, 24.2, 99.0]
shipping: [nan, 'hidden']
paymentMethodId: [nan, '668572b61ef7394b7a07f161']
multipledueDate.date: [nan, 1733785200.0, 1733958000.0]
multipledueDate.amount: [nan, 24.31, 29.65]

=== df_HD_payments_clean ===
id: ['688375402f5c9baf800ce037', '688360c3d27657ece0045357', '688360c3d27657ece0045358']
bankId: ['6697f010aa923f537703964e', '6697e93c6fb022a948097230', '6697ee29ecc2d0d7aa0e0db4']
contactId: [nan, '669a98144faadb9e99042ba1', '673245b7c31b77924705a339']
contactName: [nan, 'Onegolive Services SL', 'OpenAI, LLC']
amount: [59.29, 24.31, 49.0]
desc: ['TRANSFERENCIA DE STRIPE, CONCEPTO STRIPE.', 'STRIPE PAYOUT', 'Exchanged To Usd Main']
date: ['2024-10-21 22:00:00', '2025-07-15 22:00:00', '2024-06-30 22:00:00']
change: [nan]
documentType: ['trans', 'entry', 'purchase']
documentId: ['67c0f02610b451323f02ab4b', '66dff50c88bd646f500e282a', '66edcd8b8ba59b527e0f7a9f']

=== df_HD_purchases_clean ===
id: ['68879a1adaa2fae9720ca5cc', '688875f3ffd340ef55006bfa', '6888742d0e25ae0cd5041e87']
contact: ['673245b7c31b77924705a339', '6694f881e793fd466106a51f', '6694f7811cbbbbcbc5094183']
contactName: ['OpenAI, LLC (OpenAI, LLC)', 'Paddle.com Market Ltd (Paddle.com Market Ltd)', 'Ignacio Gaminde (Ignacio Gaminde)']
desc: ['Fra. 4 KOMBO SOLUTIONS, S.L', 'Fra. 2 KOMBO SOLUTIONS, S.L', 'Fra. 3 KOMBO SOLUTIONS, S.L']
date: ['2024-06-30 22:00:00', '2025-02-27 23:00:00', '2024-12-31 23:00:00']
dueDate: [nan, 1738882800.0, 1742857200.0]
multipledueDate: ['[]', nan]
forecastDate: [nan]
notes: [nan]
tags: ['[]', "['cogs', 'tech', 'tool']", "['2024']"]
products: ["[{'name': 'Fra. 4 KOMBO SOLUTIONS, S.L', 'desc': 'Fra. 4 KOMBO SOLUTIONS, S.L', 'price': 2916.67, 'units': 1, 'projectid': None, 'tax': 21, 'taxes': ['p_iva_21'], 'tags': [], 'discount': 0, 'retention': 0, 'weight': 0, 'costPrice': 0, 'sku': 0, 'account': '66a107fcafde0ca4240e0a40'}]", "[{'name': 'Fra. 2 KOMBO SOLUTIONS, S.L', 'desc': 'Fra. 2 KOMBO SOLUTIONS, S.L', 'price': 2916.67, 'units': 1, 'projectid': None, 'tax': 21, 'taxes': ['p_iva_21'], 'tags': [], 'discount': 0, 'retention': 0, 'weight': 0, 'costPrice': 0, 'sku': 0, 'account': '66a107fcafde0ca4240e0a40'}]", "[{'name': 'Fra. 3 KOMBO SOLUTIONS, S.L', 'desc': 'Fra. 3 KOMBO SOLUTIONS, S.L', 'price': 2916.67, 'units': 1, 'projectid': None, 'tax': 21, 'taxes': ['p_iva_21'], 'tags': [], 'discount': 0, 'retention': 0, 'weight': 0, 'costPrice': 0, 'sku': 0, 'account': '66a107fcafde0ca4240e0a40'}]"]
tax: [0.0, 612.5, 300.0]
subtotal: [2916.67, 5000.0, 1000.0]
discount: [0]
total: [3529.17, 5300.0, 1210.0]
language: ['es', nan]
status: [1, 0]
customFields: ['[]']
docNumber: ['3', '9', '4']
currency: ['eur', 'usd', 'aud']
currencyChange: [1.0, 1.140789381, 1.179676533]
paymentsTotal: [3529.17, 5300.0, 1210.0]
paymentsPending: [0.0, 3529.17, 2080.75]
paymentsRefunds: [0, 65]
paymentsDetail: [nan, "[{'id': '688375402f5c9baf800ce037', 'amount': 63.53, 'date': 1753401600, 'bankId': '6697ee29ecc2d0d7aa0e0db4'}]", "[{'id': '68837548f95ef653730b4b50', 'amount': 87.5, 'date': 1753228800, 'bankId': '6697ee29ecc2d0d7aa0e0db4'}]"]
multipledueDate.date: [nan, 1738882800.0, 1742857200.0]
multipledueDate.amount: [nan, 1210.0, 287.98]
from.id: [nan, '67ae52566b6a8d027b0a7510', '67ae54266b6a8d027b0a7604']
from.docType: [nan, 'incomingdocument']

### DATA QUALITY CHECKS

CHARTMOGUL CUSTOMERS TABLE

In [401]:
df_CM_metrics_clean.columns

Index(['date', 'mrr', 'mrr-percentage-change', 'arr', 'arr-percentage-change',
       'customer-churn-rate', 'customer-churn-rate-percentage-change',
       'mrr-churn-rate', 'mrr-churn-rate-percentage-change', 'ltv',
       'ltv-percentage-change', 'customers', 'customers-percentage-change',
       'asp', 'asp-percentage-change', 'arpa', 'arpa-percentage-change',
       'year', 'month', 'month_start'],
      dtype='object')

In [326]:
df_CM_customers_clean.head(1)

,id,uuid,external_id,name,email,status,customer-since,data_source_uuid,data_source_uuids,external_ids,company,country,state,city,zip,lead_created_at,free_trial_started_at,mrr,arr,billing-system-url,chartmogul-url,billing-system-type,currency,currency-sign,owner,website_url,attributes.tags,address.country,address.state,address.city,address.address_zip,attributes.hubspot.Company_owner,attributes.hubspot.Lifecycle_Stage,attributes.hubspot.Latest_Source,attributes.hubspot.Original_Source,attributes.stripe.userId,attributes.stripe.companyId,attributes.hubspot.Industry,attributes.hubspot.Time_Last_Seen,attributes.hubspot.Type
0,177867729,cus_9a55ecba-bcdc-4d19-89d1-05ddfac08906,cus_PubGEWYD0zJS7r,Edicom Capital,lgalceran@edicom.es,Active,2024-04-12T15:30:48+00:00,ds_78983044-48ff-11ef-a3c9-aba08b7ca782,['ds_78983044-48ff-11ef-a3c9-aba08b7ca782'],['cus_PubGEWYD0zJS7r'],NaN,ES,NaN,Paterna,46980,NaN,NaN,30135,361620,https://dashboard.stripe.com/customers/cus_Pub...,https://app.chartmogul.com/#/customers/1778677...,Stripe,EUR,€,NaN,https://edicom.es,[],Spain,NaN,Paterna,46980,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [327]:
df_customer_since_null = df_CM_customers_clean[df_CM_customers_clean['customer-since'].isnull()]
df_customer_since_null

,id,uuid,external_id,name,email,status,customer-since,data_source_uuid,data_source_uuids,external_ids,company,country,state,city,zip,lead_created_at,free_trial_started_at,mrr,arr,billing-system-url,chartmogul-url,billing-system-type,currency,currency-sign,owner,website_url,attributes.tags,address.country,address.state,address.city,address.address_zip,attributes.hubspot.Company_owner,attributes.hubspot.Lifecycle_Stage,attributes.hubspot.Latest_Source,attributes.hubspot.Original_Source,attributes.stripe.userId,attributes.stripe.companyId,attributes.hubspot.Industry,attributes.hubspot.Time_Last_Seen,attributes.hubspot.Type
128,177867712,cus_10085ea2-6a99-49a1-b2f8-0732a2995c1e,cus_PryMX9IlRfVVNo,Jose Manuel Gomez,jmgomez@edicomgroup.com,New Lead,NaN,ds_78983044-48ff-11ef-a3c9-aba08b7ca782,['ds_78983044-48ff-11ef-a3c9-aba08b7ca782'],['cus_PryMX9IlRfVVNo'],Empresa que ayuda a cumplir con las legislacio...,ES,NaN,Paterna,46980,NaN,NaN,0,0,https://dashboard.stripe.com/customers/cus_Pry...,https://app.chartmogul.com/#/customers/1778677...,Stripe,EUR,€,NaN,https://edicomgroup.com,[],Spain,NaN,Paterna,46980,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
129,177867714,cus_bef671f9-1026-4e2d-93bb-9681d2b04284,cus_PuVDmR1eFG8OkG,Alessandro Pintaudi,alessandro.pintaudi@gmail.com,New Lead,NaN,ds_78983044-48ff-11ef-a3c9-aba08b7ca782,['ds_78983044-48ff-11ef-a3c9-aba08b7ca782'],['cus_PuVDmR1eFG8OkG'],Test account,ES,NaN,Barcelona,08013,2025-06-26 10:49:53+00:00,2025-06-26T10:49:53.000Z,0,0,https://dashboard.stripe.com/customers/cus_PuV...,https://app.chartmogul.com/#/customers/1778677...,Stripe,EUR,€,NaN,NaN,[],Spain,NaN,Barcelona,08013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
130,177868037,cus_41ea78e0-f2a0-4d0b-bf49-cbbff27bf48a,10482378434,Simplr,contact@simplr.io,New Lead,NaN,ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c,['ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c'],['10482378434'],Simplr,ES,NaN,Barcelona,NaN,2024-03-06 13:44:46.716000+00:00,NaN,0,0,https://app-eu1.hubspot.com/contacts/143433615...,https://app.chartmogul.com/#/customers/1778680...,HubSpot,EUR,€,NaN,https://simplr.io,[],Spain,NaN,Barcelona,NaN,1.395566e+09,opportunity,NaN,NaN,NaN,NaN,CONSUMER_SERVICES,NaN,NaN
131,177868039,cus_cf95b46f-3579-4881-8c67-c3fe985216a3,8684435189,Bookiply,NaN,New Lead,NaN,ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c,['ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c'],['8684435189'],Bookiply,NaN,NaN,NaN,NaN,2023-10-08 09:13:06.504000+00:00,NaN,0,0,https://app-eu1.hubspot.com/contacts/143433615...,https://app.chartmogul.com/#/customers/1778680...,HubSpot,EUR,€,NaN,NaN,[],NaN,NaN,NaN,NaN,1.395565e+09,opportunity,NaN,NaN,NaN,NaN,LEISURE_TRAVEL_TOURISM,NaN,PROSPECT
132,177868040,cus_d6710e1f-bf74-4bdb-b898-73a642558e02,10721052861,Domenec Cornudella,domenec.cornudella@ferchau.com,New Lead,NaN,ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c,['ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c'],['10721052861'],Ferchau,NaN,NaN,NaN,NaN,2024-03-20 09:36:46.531000+00:00,NaN,0,0,https://app-eu1.hubspot.com/contacts/143433615...,https://app.chartmogul.com/#/customers/1778680...,HubSpot,EUR,€,NaN,https://ferchau.com,[],NaN,NaN,NaN,NaN,1.395565e+09,lead,OFFLINE,OFFLINE,NaN,NaN,NaN,NaN,NaN
133,177868041,cus_33c702aa-f169-4924-93f6-c7f150b8dd8a,8684435397,RMG,NaN,New Lead,NaN,ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c,['ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c'],['8684435397'],RMG,NaN,NaN,NaN,NaN,2023-10-08 09:19:26.109000+00:00,NaN,0,0,https://app-eu1.hubspot.com/contacts/143433615...,https://app.chartmogul.com/#/customers/1778680...,HubSpot,EUR,€,NaN,NaN,[],NaN,NaN,NaN,NaN,1.395565e+09,opportunity,NaN,NaN,NaN,NaN,MANAGEMENT_CONSULTING,NaN,RESELLER
134,177868042,cus_22a58e10-e868-47d2-9f5c-7cc862bef39d,10482378173,Signaturit,contact@signaturit.com,New Lead,NaN,ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c,"['ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c', 'd...","['21070005186', '10482378173', '10337176000']",Signaturit,NaN,NaN,NaN,NaN,2024-03-06 13:42:12.806000+00:00,NaN,0,0,https://app-eu1.hubspot.com/contacts/143433615...,https://app.chartmogul.com/#/customers/1778680...,HubSpot,EUR,€,NaN,https://signaturit.com,['merged-customer'],NaN,NaN,NaN,NaN,1.395566e+09,opportunity,OFFLINE,OFFLINE,NaN,NaN,COMPUTER_SOFTWARE,NaN,NaN
135,177868043,cus_cbf74e15-2d2b-4a16-b1e4-f1f8c3d25522,10481321666,Factorial HR,contact@factorialhr.com,New Lead,NaN,ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c,['ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c'],['10481321666'],Factorial HR,ES,NaN,Barcelona,08005,2024-08-27 14:27:11.574000+00:00,NaN,0,0,https://app-eu1.hubspot.com/contacts/143433615...,https://app.chartmogul.com/#/customers/1778680...,HubSpot,EUR,€,NaN,https://factorialhr.com,[],Spain,NaN,Barcelona,08005,1.395566e+09,opportunity,OFFLINE,OFFLINE,NaN,NaN,HUMAN_RESOURCES,NaN,NaN
136,177868044,cus_1c3fe679-dac4-4617-a43b-b2ab2d459f69,12555297251,Sara,sara@europelanguagejobs.com,New Lead,NaN,ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c,"['ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c', 'd...","['12555297251', '19560259305', 'cus_Qzw6hPIbmv...",NaN,NaN,NaN,NaN,NaN,2024-06-18 12:25:09.994000+00:00,NaN,0,0,https://app-eu1.hubspot.com/contacts/143433615...,https://app.chartmogul.com/#/customers/1778680...,HubSpot,EUR,€,NaN,https://europelanguagejobs.com,['merged-customer'],NaN,NaN,NaN,NaN,1.777133e+09,opportunity,OFFLINE,OFFLINE,NaN,NaN,NaN,NaN,NaN
137,177868046,cus_01f94206-5c30-4dbc-9e71-cbd5fbbc478d,9616713440,IAG,contact@italianangels.net,New Lead,NaN,ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c,['ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c'],['9616713440'],IAG,IT,NaN,Milan,20123,2024-01-16 16:01:01.513000+00:00,NaN,0,0,https://app-eu1.hubspot.com/contacts/143433615...,https://app.chartmogul.com/#/customers/1778680...,HubSpot,EUR,€,NaN,https://italianangels.net,[],Italy,NaN,Milan,20123,1.395566e+09,lead,OFFLINE,OFFLINE,NaN,NaN,VENTURE_CAPITAL_PRIVATE_EQUITY,NaN,NaN
138,177868047,cus_6780f28b-b6c2-4fe6-a4f2-3ce65efd04d1,8684435192,Teleperformance,NaN,New Lead,NaN,ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c,['ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c'],['8684435192'],Teleperformance,NaN,NaN,NaN,NaN,2023-10-08 09:14:13.204000+00:00,NaN,0,0,https://app-eu1.hubspot.com/contacts/143433615...,https://app.chartmogul.com/#/customers/1778680...,HubSpot,EUR,€,NaN,NaN,[],NaN,NaN,NaN,NaN,1.395565e+09,opportunity,NaN,NaN,NaN,NaN,INFORMATION_TECHNOLOGY_AND_SERVICES,NaN,PROSPECT
139,177868048,cus_b677cefa-1fc8-443e-b673-510d6528e33a,9900919758,Backfuture,contact@backfuture.vc,New Lead,NaN,ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c,['ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c'],['9900919758'],Backfuture,NaN,NaN,NaN,NaN,2024-01-31 17:25:14.099000+00:00,NaN,0,0,https://app-eu1.hubspot.com/contacts/143433615...,https://app.chartmogul.com/#/customers/1778680...,HubSpot,EUR,€,NaN,https://backfuture.vc,[],NaN,NaN,NaN,NaN,1.395566e+09,lead,OFFLINE,OFFLINE,NaN,NaN,NaN,NaN,NaN
140,177868049,cus_b77b09e1-33b3-431f-8a37-45d74ab56bb0,12555243488,Jorge Augusto Reves Leguia,jreves1990@gmail.com,New Lead,NaN,ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c,['ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c'],['12555243488'],Shaper GAP,NaN,NaN,NaN,NaN,2024-06-27 08:19:16.217000+00:00,NaN,0,0,https://app-eu1.hubspot.com/contacts/143433615...,https://app.chartmogul.com/#/customers/1778680...,HubSpot,EUR,€,NaN,NaN,[],NaN,NaN,NaN,NaN,1.777133e+09,opportunity,OFFLINE,OFFLINE,NaN,NaN,NaN,NaN,NaN
141,177868050,cus_c9f48713-2737-44fc-8e7c-287f7b0498bf,12681359808,Juanjo Martinez,NaN,New Lead,NaN,ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c,['ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c'],['12681359808'],Proyectos de F&B y gestión conceptos gastronóm...,NaN,NaN,NaN,NaN,2024-07-04 14:21:39.376000+00:00,NaN,0,0,https://app-eu1.hubspot.com/contacts/143433615...,https://app.chartmogul.com/#/customers/1778680...,HubSpot,EUR,€,NaN,NaN,[],NaN,NaN,NaN,NaN,1.703147e+09,lead,OFFLINE,OFFLINE,NaN,NaN,NaN,NaN,NaN
142,177868051,cus_3666d10b-2546-4f81-9f67-28440d572993,9613740476,Stephan Weber,stephan@project-b.dev,New Lead,NaN,ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c,['ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c'],['9613740476'],project b,DE,NaN,Munich,NaN,2024-01-16 15:59:28.710000+00:00,NaN,0,0,https://app-eu1.hubspot.com/contacts/143433615...,https://app.chartmogul.com/#/customers/1778680...,HubSpot,EUR,€,NaN,https://project-b.dev,[],Germany,NaN,Munich,NaN,1.395566e+09,lead,OFFLINE,OFFLINE,NaN,NaN,NaN,NaN,NaN
143,177868053,cus_fafa214a-bdae-4399-a75e-76667ec8a36c,12555821267,Eugenio García Martín,eugenio.garciamartin@gmail.com,New Lead,NaN,ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c,['ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c'],['12555821267'],FIATC Seguros,NaN,NaN,NaN,NaN,2024-06-27 08:07:25.115000+00:00,NaN,0,0,https://app-eu1.hubspot.com/contacts/143433615...,https://app.chartmogul.com/#/customers/1778680...,HubSpot,EUR,€,NaN,NaN,[],NaN,NaN,NaN,NaN,1.777133e+09,opportunity,OFFLINE,OFFLINE,NaN,NaN,NaN,NaN,NaN
144,177868054,cus_ec928300-be2f-4899-b7cb-17a94f710b47,9901037017,Ubaldo Mafrici,ubaldo@techshop.capital,New Lead,NaN,ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c,['ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c'],['9901037017'],techshop.capital,IT,NaN,Coldbrook,B4R 1C5,2024-01-31 17:06:25.862000+00:00,NaN,0,0,https://app-eu1.hubspot.com/contacts/143433615...,https://app.chartmogul.com/#/customers/1778680...,HubSpot,EUR,€,NaN,https://techshop.capital,[],Italy,NaN,Coldbrook,B4R 1C5,1.395566e+09,lead,OFFLINE,OFFLINE,NaN,NaN,CAPITAL_MARKETS,NaN,NaN
145,177868055,cus_141ff000-5a9c-45b1-8c7e-b895fe33eac5,12653108961,Sigesa,NaN,New Lead,NaN,ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c,['ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c'],['12653108961'],Sigesa,NaN,NaN,NaN,NaN,2024-07-02 13:17:01.923000+00:00,NaN,0,0,https://app-eu1.hubspot.com/contacts/143433615...,https://app.chartmogul.com/#/customers/1778680...,HubSpot,EUR,€,NaN,https://sigesa.com,[],NaN,NaN,NaN,NaN,1.777133e+09,opportunity,OFFLINE,OFFLINE,NaN,NaN,NaN,NaN,NaN
146,177868056,cus_95e38f1d-f9fd-443d-a60e-a13fff6b17e6,12749009640,ANCO,NaN,New Lead,NaN,ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c,['ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c'],['12749009640'],ANCO,NaN,NaN,NaN,NaN,2024-07-05 14:15:42.908000+00:00,NaN,0,0,https://app-eu1.hubspot.com/contacts/143433615...,https://app.chartmogul.com/#/customers/1778680...,HubSpot,EUR,€,NaN,https://anco.es,[],NaN,NaN,NaN,NaN,1.777133e+09,opportunity,OFFLINE,OFFLINE,NaN,NaN,NaN,NaN,NaN
147,177868057,cus_aa10899b-97d5-497f-a83c-5e1b13e925e9,12672893904,Zerto,NaN,New Lead,NaN,ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c,['ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c'],['12672893904'],Zerto,NaN,NaN,NaN,NaN,2024-07-04 07:37:07.245000+00:00,NaN,0,0,https://app-eu1.hubspot.com/contacts/143433615...,https://app.chartmogul.com/#/customers/1778680...,HubSpot,EUR,€,NaN,https://hpe.com,[],NaN,NaN,NaN,NaN,1.777133e+09,opportunity,OFFLINE,OFFLINE,NaN,NaN,COMPUTER_NETWORK_SECURITY,NaN,NaN
148,177868058,cus_2552b208-730d-418c-8be2-d7cede8ae813,12437478109,David Redondo,NaN,New Lead,NaN,ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c,['ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c'],['12437478109'],Stealth Startup,US,GA,Atlanta,30307,2024-06-19 11:28:41.197000+00:00,NaN,0,0,https://app-eu1.hubspot.com/contacts/143433615...,https://app.chartmogul.com/#/customers/1778680...,HubSpot,EUR,€,NaN,NaN,[],United States,Georgia,Atlanta,30307,1.599711e+09,lead,OFFLINE,OFFLINE,NaN,NaN,COMPUTER_SOFTWARE,NaN,NaN
149,177868059,cus_9b0b8f39-b652-4bae-9d0a-1d45333a1615,9459882732,Tripadvisor,contact@tripadvisor.com,New Lead,NaN,ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c,['ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c'],['9459882732'],Tripadvisor,US,MA,Needham,02494,2024-01-08 16:45:03.027000+00:00,NaN,0,0,https://app-eu1.hubspot.com/contacts/143433615...,https://app.chartmogul.com/#/customers/1778680...,HubSpot,EUR,€,NaN,https://tripadvisor.com,[],United States,Massachusetts,Needham,02494,1.395566e+09,opportunity,OFFLINE,OFFLINE,NaN,NaN,LEISURE_TRAVEL_TOURISM,NaN,NaN
150,177868060,cus_501e2578-c1ec-4d25-a33d-dc208589d6b0,12461325009,Smart Commerce 21,contact@www.smartcommerce21.com,New Lead,NaN,ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c,['ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c'],['12461325009'],Smart Commerce 21,ES,NaN,Barcelona,08006,2024-06-21 08:11:09.402000+00:00,NaN,0,0,https://app-eu1.hubspot.com/contacts/143433615...,https://app.chartmogul.com/#/customers/1778680...,HubSpot,EUR,€,NaN,https://smartcommerce21.com,[],Spain,NaN,Barcelona,08006,1.560299e+09,lead,OFFLINE,OFFLINE,NaN,NaN,NaN,NaN,NaN
151,177868061,cus_380fd2cb-6fc9-46c3-bf3a-7e5ce3c824f6,12555731899,Novonesis,NaN,New Lead,NaN,ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c,['ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c'],['12555731899'],Novonesis,NaN,NaN,NaN,NaN,2024-06-27 08:40:32.973000+00:00,NaN,0,0,https://app-eu1.hubspot.com/contacts/143433615...,https://app.chartmogul.com/#/customers/1778680...,HubSpot,EUR,€,NaN,https://novonesis.com,[],NaN,NaN,NaN,NaN,1.777133e+09,opportunity,OFFLINE,OFFLINE,NaN,NaN,BIOTECHNOLOGY,NaN,NaN
152,177868062,cus_ca032fe2-6305-44f5-a7eb-d216dd8d54fd,12634388948,FASTCO,contact@mahou-sanmiguel.com,New Lead,NaN,ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c,['ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c'],['12634388948'],FASTCO,NaN,NaN,NaN,NaN,2024-07-03 14:35:03.362000+00:00,NaN,0,0,https://app-eu1.hubspot.com/contacts/143433615...,https://app.chartmogul.com/#/customers/1778680...,HubSpot,EUR,€,NaN,https://fastcogroup.com,[],NaN,NaN,NaN,NaN,1.777133e+09,opportunity,OFFLINE,OFFLINE,NaN,NaN,NaN,NaN,NaN
153,177868063,cus_b2fa142c-c013-4913-a72f-0a9ea725a253,9459132639,Andrea Di Gioia,NaN,New Lead,NaN,ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c,['ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c'],['9459132639'],SumUp,GB,NaN,London,W1F 7JB,2024-01-08 16:26:12.767000+00:00,NaN,0,0,https://app-eu1.hubspot.com/contacts/143433615...,https://app.chartmogul.com/#/customers/1778680...,HubSpot,EUR,€,NaN,NaN,[],United Kingdom,NaN,London,W1F 7JB,1.395566e+09,opportunity,OFFLINE,OFFLINE,NaN,NaN,FINANCIAL_SERVICES,NaN,NaN
154,177868064,cus_9a158481-35d0-46f1-99a3-1fa95fb00ef9,9941779192,Big Sur Ventures,contact@bigsurventures.vc,New Lead,NaN,ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c,['ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c'],['9941779192'],Big Sur Ventures,ES,NaN,Madrid,28036,2024-02-07 13:57:04.135000+00:00,NaN,0,0,https://app-eu1.hubspot.com/contacts/143433615...,https://app.chartmogul.com/#/customers/1778680...,HubSpot,EUR,€,NaN,https://bigsurventures.vc,[],Spain,NaN,Madrid,28036,1.395566e+09,lead,OFFLINE,OFFLINE,NaN,NaN,NaN,NaN,NaN
155,177868065,cus_b33a3ace-bd6c-4618-8500-5a889d026597,8684435185,Brigitte Hidalgo,brigitte.hidalgo@weekendesk.es,New Lead,NaN,ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c,['ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c'],['8684435185'],Weekendesk,NaN,NaN,NaN,NaN,2023-10-08 09:12:06.072000+00:00,NaN,0,0,https://app-eu1.hubspot.com/contacts/143433615...,https://app.chartmogul.com/#/customers/1778680...,HubSpot,EUR,€,NaN,https://weekendesk.es,[],NaN,NaN,NaN,NaN,1.395565e+09,lead,OFFLINE,OFFLINE,NaN,NaN,LEISURE_TRAVEL_TOURISM,NaN,PROSPECT
156,177868066,cus_78c2c147-ece8-4698-8c93-2d32bc50fbbe,9769991152,Playoffnations,contact@playoffnations.com,New Lead,NaN,ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c,['ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c'],['9769991152'],Playoffnations,ES,NaN,Madrid,28006,2024-01-26 10:17:22.073000+00:00,NaN,0,0,https://app-eu1.hubspot.com/contacts/143433615...,https://app.chartmogul.com/#/customers/1778680...,HubSpot,EUR,€,NaN,https://playoffnations.com,[],Spain,NaN,Madrid,28006,1.395566e+09,lead,OFFLINE,OFFLINE,NaN,NaN,MARKETING_AND_ADVERTISING,NaN,NaN
157,177868067,cus_421cf573-c2a7-4824-b175-cffeaffe74fd,12699840968,ABAST,NaN,New Lead,NaN,ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c,['ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c'],['12699840968'],ABAST,NaN,NaN,NaN,NaN,2024-07-05 09:08:31.279000+00:00,NaN,0,0,https://app-eu1.hubspot.com/contacts/143433615...,https://app.chartmogul.com/#/customers/1778680...,HubSpot,EUR,€,NaN,NaN,[],NaN,NaN,NaN,NaN,1.777133e+09,opportunity,OFFLINE,OFFLINE,NaN,NaN,NaN,NaN,NaN
158,177868068,cus_ab371ed8-6407-476e-ba82-ef2a387f19bc,12555297511,Konecta,NaN,New Lead,NaN,ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c,['ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c'],['12555297511'],Konecta,NaN,NaN,NaN,NaN,2024-06-27 08:30:12.909000+00:00,NaN,0,0,https://app-eu1.hubspot.com/contacts/143433615...,https://app.chartmogul.com/#/customers/1778680...,HubSpot,EUR,€,NaN,NaN,[],NaN,NaN,NaN,NaN,1.777133e+09,lead,NaN,NaN,NaN,NaN,NaN,NaN,NaN
159,177868069,cus_4314950c-7d7e-4c9f-811a-8bfe471cce0c,9459097835,Karmen,contact@karmen.io,New Lead,NaN,ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c,['ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c'],['9459097835'],Karmen,FR,NaN,Paris,75009,2024-01-08 16:19:39.568000+00:00,NaN,0,0,https://app-eu1.hubspot.com/contacts/143433615...,https://app.chartmogul.com/#/customers/1778680...,HubSpot,EUR,€,NaN,https://karmen.io,[],France,NaN,Paris,75009,1.395566e+09,opportunity,NaN,NaN,NaN,NaN,FINANCIAL_SERVICES,NaN,NaN
160,177868070,cus_29cef257-9fbd-4e47-97da-de09d0486d26,8684435422,Hosco,NaN,New Lead,NaN,ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c,['ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c'],['8684435422'],Hosco,NaN,NaN,NaN,NaN,2023-10-08 09:30:26.609000+00:00,NaN,0,0,https://app-eu1.hubspot.com/contacts/143433615...,https://app.chartmogul.com/#/customers/1778680...,HubSpot,EUR,€,NaN,https://hosco.com,[],NaN,NaN,NaN,NaN,1.395565e+09,lead,OFFLINE,OFFLINE,NaN,NaN,LEISURE_TRAVEL_TOURISM,NaN,PARTNER
161,177868071,cus_06494d6b-b396-40ff-b6a1-42794f57d7d1,12636340454,Antonio N.,NaN,New Lead,NaN,ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c,['ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c'],['12636340454'],Turiscool,NaN,NaN,NaN,NaN,2024-07-02 13:29:04.908000+00:00,NaN,0,0,https://app-eu1.hubspot.com/contacts/143433615...,https://app.chartmogul.com/#/customers/1778680...,HubSpot,EUR,€,NaN,NaN,[],NaN,NaN,NaN,NaN,1.560299e+09,opportunity,OFFLINE,OFFLINE,NaN,NaN,EDUCATION_MANAGEMENT,NaN,NaN
162,177868072,cus_b548cb8d-22f3-45cc-b626-dd706fcd6a35,12782436839,Jose,josemiguel.ortuno@hanbai.io,New Lead,NaN,ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c,"['ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c', 'd...","['12782436839', 'cus_Qzw99v8Xu7H9yT']",NaN,NaN,NaN,NaN,NaN,2024-07-11 14:52:25.139000+00:00,NaN,0,0,https://app-eu1.hubspot.com/contacts/143433615...,https://app.chartmogul.com/#/customers/1778680...,HubSpot,EUR,€,NaN,https://hanbai.io,['merged-customer'],NaN,NaN,NaN,NaN,1.777133e+09,customer,OFFLINE,OFFLINE,NaN,NaN,NaN,NaN,NaN
163,177868073,cus_e5be4e21-edbb-4a5b-9bac-e09ca65a57c9,8684987597,Typeform,contact@typeform.com,New Lead,NaN,ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c,['ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c'],['8684987597'],Typeform,NaN,NaN,NaN,NaN,2023-10-08 09:25:45.663000+00:00,NaN,0,0,https://app-eu1.hubspot.com/contacts/143433615...,https://app.chartmogul.com/#/customers/1778680...,HubSpot,EUR,€,NaN,https://typeform.com,[],NaN,NaN,NaN,NaN,1.395565e+09,opportunity,OFFLINE,OFFLINE,NaN,NaN,INFORMATION_TECHNOLOGY_AND_SERVICES,NaN,PROSPECT
164,177868074,cus_e61d842d-191b-4e55-90ca-eb7b94cb9af4,8684987583,brooktec,NaN,New Lead,NaN,ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c,['ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c'],['8684987583'],brooktec,NaN,NaN,NaN,NaN,2023-10-08 09:22:09.798000+00:00,NaN,0,0,https://app-eu1.hubspot.com/contacts/143433615...,https://app.chartmogul.com/#/customers/1778680...,HubSpot,EUR,€,NaN,https://brooktec.com,[],NaN,NaN,NaN,NaN,1.395565e+09,lead,OFFLINE,OFFLINE,NaN,NaN,INFORMATION_TECHNOLOGY_AND_SERVICES,NaN,PROSPECT
165,177868075,cus_7380ed9d-c9de-4110-b5cf-55443b98db5c,9459588846,Pablo Viñuela,NaN,New Lead,NaN,ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c,['ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c'],['9459588846'],HealthAtom - Dentalink - Medilink,CL,NaN,"Santiago, Las Condes",9270000,2024-01-08 16:23:15.085000+00:00,NaN,0,0,https://app-eu1.hubspot.com/contacts/143433615...,https://app.chartmogul.com/#/customers/1778680...,HubSpot,EUR,€,NaN,NaN,[],Chile,NaN,"Santiago, Las Condes",9270000,1.395566e+09,opportunity,OFFLINE,OFFLINE,NaN,NaN,NaN,NaN,NaN

In [328]:
df_CM_customers_clean['status'].value_counts()

status
Active       77
New Lead     72
Cancelled    47
Past Due      4
Name: count, dtype: int64

In [329]:
# All records in DF Customers that are null in the 'customer-since' column are null because they are leads. So they are nulls with a meaning. They are correct.

In [393]:
len(df_HD_purchases_clean)

447

In [398]:
df_test = df_HD_purchases_clean.copy()

df_test["tax_eur"] = df_test["tax"] * df_test["currencyChange"]
df_test["subtotal_eur"] = df_test["subtotal"] * df_test["currencyChange"]
df_test["total_eur"] = df_test["total"] * df_test["currencyChange"]

print(df_test[["tax_eur", "subtotal_eur", "total_eur"]].head())

   tax_eur  subtotal_eur    total_eur
0    612.5   2916.670000  3529.170000
1      0.0   3695.235779  3695.235779
2      0.0     26.998853    26.998853
3      0.0     63.530000    63.530000
4      0.0     87.500000    87.500000

In [397]:
df_HD_purchases_clean[(df_HD_purchases_clean['total'].isna()) | (df_HD_purchases_clean['subtotal'].isna()) | (df_HD_purchases_clean['tax'].isna())]

Empty DataFrame
Columns: [id, contact, contactName, desc, date, dueDate, multipledueDate, forecastDate, notes, tags, products, tax, subtotal, discount, total, language, status, customFields, docNumber, currency, currencyChange, paymentsTotal, paymentsPending, paymentsRefunds, paymentsDetail, multipledueDate.date, multipledueDate.amount, from.id, from.docType]
Index: []

In [390]:
df_CM_metrics_clean.columns

Index(['date', 'mrr', 'mrr-percentage-change', 'arr', 'arr-percentage-change',
       'customer-churn-rate', 'customer-churn-rate-percentage-change',
       'mrr-churn-rate', 'mrr-churn-rate-percentage-change', 'ltv',
       'ltv-percentage-change', 'customers', 'customers-percentage-change',
       'asp', 'asp-percentage-change', 'arpa', 'arpa-percentage-change',
       'year', 'month', 'month_start'],
      dtype='object')

In [389]:
df_CM_metrics_clean.head(12)

,date,mrr,mrr-percentage-change,arr,arr-percentage-change,customer-churn-rate,customer-churn-rate-percentage-change,mrr-churn-rate,mrr-churn-rate-percentage-change,ltv,ltv-percentage-change,customers,customers-percentage-change,asp,asp-percentage-change,arpa,arpa-percentage-change,year,month,month_start
0,2024-03-31,0,0.0,0,0.0,0.00,0.0,0.00,0.0,0,0.0,0,0.0,0,0.0,0,0.0,2024,3,2024-03-01
1,2024-04-30,27900,0.0,334800,0.0,0.00,0.0,0.00,0.0,0,0.0,6,0.0,4650,0.0,4650,0.0,2024,4,2024-04-01
2,2024-05-31,56400,0.0,676800,0.0,0.00,0.0,-17.56,0.0,0,0.0,10,0.0,5900,0.0,5640,0.0,2024,5,2024-05-01
3,2024-06-30,75500,0.0,906000,0.0,0.00,0.0,12.23,0.0,0,0.0,13,0.0,8667,0.0,5807,0.0,2024,6,2024-06-01
4,2024-07-31,153728,0.0,1844736,0.0,15.38,0.0,-10.26,0.0,0,0.0,16,0.0,14096,0.0,9608,0.0,2024,7,2024-07-01
5,2024-08-31,160479,0.0,1925748,0.0,0.00,0.0,-4.39,0.0,391757,0.0,16,0.0,0,0.0,10029,0.0,2024,8,2024-08-01
6,2024-09-30,190652,0.0,2287824,0.0,6.25,0.0,-3.35,0.0,323789,0.0,23,0.0,3100,0.0,8289,0.0,2024,9,2024-09-01
7,2024-10-31,318576,0.0,3822912,0.0,4.35,0.0,5.49,0.0,275761,0.0,32,0.0,12582,0.0,9955,0.0,2024,10,2024-10-01
8,2024-11-30,367665,0.0,4411980,0.0,9.38,0.0,8.10,0.0,242586,0.0,35,0.0,12480,0.0,10504,0.0,2024,11,2024-11-01
9,2024-12-31,379376,0.0,4552512,0.0,11.43,0.0,8.60,0.0,169490,0.0,38,0.0,6189,0.0,9983,0.0,2024,12,2024-12-01
10,2025-01-31,427550,0.0,5130600,0.0,7.89,0.0,-5.25,0.0,144243,0.0,38,0.0,9420,0.0,11251,0.0,2025,1,2025-01-01
11,2025-02-28,512797,0.0,6153564,0.0,5.26,0.0,1.49,0.0,163099,0.0,48,0.0,7635,0.0,10683,0.0,2025,2,2025-02-01

### METRICS

MRR

In [330]:
# DEFINITION:
# Monthly Recurring Revenue - The amount of predictable profit obtained every month from subscriptions

# FORMULA:
# [ MRR = Num. Monthly Customers * Sum of their Subscriptions ]

# SOURCE / PROCESS FOR CREATING:
# Taken directly from Chartmogul's Metrics Table
# ---
# Otherwise it could be calculated by finding the *Number of New Customers* for the given month, 
# multiplied by the *Sum of Money each of them pays for a Monthly Subscription*.
# ---

# If we want to validate Chartmogul's metric here we can start by finding the *Number of New Monthly Customers*. 
# We can either do this by:
# 1. Looking at the date in the 'customer_since' column in the Chartmogul Customers Table
# 2. Finding the first invoice for a given customer in the Holded Invoices Table
# 3. Filtering for 'client' in the 'type' column of the Holded Contacts Table, 
#    then merging with the Holded Payments Table on the respective columns 'id' and 'contactId'.

In [331]:
# Filter Contacts table to keep only those with 'client' in the 'type' column
df_clients = df_HD_contacts_clean[df_HD_contacts_clean['type'] == 'client']

In [332]:
# Join filtered clients from Contacts table with their related payments in the Payments table  
df_joined_clients = pd.merge(
    df_clients,
    df_HD_payments_clean,
    left_on='id',
    right_on='contactId',
    how='inner'
)

In [333]:
# Function to check how to map specific customer records between two Chartmogul tables
def check_column_match(df1, df2, col_df1, col_df2):
    """
    Check exact matches between a column in ChartMogul data 
    and a column in Holded data.
    
    Parameters:
        df_cm (pd.DataFrame): ChartMogul dataframe
        df_hd (pd.DataFrame): Holded dataframe
        cm_col (str): column name in ChartMogul dataframe
        hd_col (str): column name in Holded dataframe
    
    Returns:
        dict: match statistics
    """
    # Ensure columns exist
    if col_df1 not in df1.columns:
        raise ValueError(f"Column '{col_df1}' not found in '{df1}' dataframe.")
    if col_df2 not in df2.columns:
        raise ValueError(f"Column '{col_df2}' not found in '{df2}' dataframe.")

    # Get unique, non-null values for comparison
    cm_values = set(df1[col_df1].dropna().astype(str).str.strip())
    hd_values = set(df2[col_df2].dropna().astype(str).str.strip())

    # Find matches
    matches = cm_values.intersection(hd_values)

    # Stats
    cm_total = len(cm_values)
    hd_total = len(hd_values)
    match_count = len(matches)

    stats = {
        "cm_unique_values": cm_total,
        "hd_unique_values": hd_total,
        "matches_found": match_count,
        "percent_of_cm_matched": match_count / cm_total * 100 if cm_total else 0,
        "percent_of_hd_matched": match_count / hd_total * 100 if hd_total else 0,
        "matched_values": matches
    }

    return stats

# Example usage:
# stats = check_column_match(df_CM_customers_clean, df_HD_invoices_clean, "external_id", "contact")
# print(stats)

In [334]:
stats = check_column_match(df_HD_contacts_clean, df_HD_payments_clean, "id", "contactId")
print(stats)

{'cm_unique_values': 500, 'hd_unique_values': 268, 'matches_found': 191, 'percent_of_cm_matched': 38.2, 'percent_of_hd_matched': 71.26865671641791, 'matched_values': {'67c878404e7cee4d280053c0', '67f29a516ce52a70fa0ca5ce', '66a0ed046628d94867097eb6', '66a36ab8424d7a73f30b466b', '67ec0bbb7669e0088a063e03', '6721145f32b39c15d70607a3', '681a2e233298fa31180ca1d2', '67ec0bbb7669e0088a063e05', '6852bf0ed7f7b87ec2042a11', '66c311a2eafc2b9a120d052b', '669a98144faadb9e99042ba1', '66ed8ba755ab20f72a0064a7', '673f6789b2303b9463004b46', '67e6c123e62087457b0b7268', '67ae289cd92c82a3ed0c5163', '66a0e5e1061badb033056cb8', '681a35b6cd0f1cdc74001719', '67ec0bbb7669e0088a063e02', '6852bf0dd7f7b87ec2042a0f', '673245b7c31b77924705a339', '67ae289cd92c82a3ed0c5180', '679aa7946148fd046c0961ca', '6694fc239e07ff6dfc052826', '67f39bb8925929cb380fa8f1', '66e426d637dbc93c9b0c1610', '66c98b716f2fd2105a0d2cc6', '66db1e7d48c5e1938703d8e1', '681a5579f1ea6b91650b2f65', '66a0e85b1951a0a871019577', '67ae54f92082bee6bb02b284', '67f38fb6856c4168cd00ca3d', '68236f3862f063a31d05476f', '683581fcddc06c80f30910a7', '6694ffa7d2c07847d10f9658', '67ae289bd92c82a3ed0c5136', '67e6c122e62087457b0b7257', '68273d358a011e371c00e1d4', '67e6c121e62087457b0b720b', '67e6c121e62087457b0b71fd', '67ae28a0d92c82a3ed0c5255', '672ca6594cc0add3080b6460', '67e6c11de62087457b0b7130', '679249fbf4ba6ceb6604769e', '66a0ea99d6f58778f403e2e8', '66b8996eb496e7f9210a42d0', '67e6c11ce62087457b0b7101', '67911f90a1b85762aa0fa323', '66ca170e07b4bebc8d0dacd5', '67ae2899d92c82a3ed0c50ad', '67ae289bd92c82a3ed0c5144', '66d970bff4886c4bdd0671ec', '6740d4f63f6791c59c0b65e6', '67af0d09f1fe256297038376', '66a0eb77aaa9294fd70f5222', '67e6c128e62087457b0b73a3', '68405e6a4e669fd39b05e1a3', '66e853461726c08ac9012017', '675976a014fd5d9ff3099fa4', '66bf7e038dc8505449015afb', '66bb168bffa1a257fd08a465', '66c0a733d027acacbf09d8ea', '67533ab9cae0f70a83054115', '67e6c124e62087457b0b72c6', '6721145e32b39c15d706075d', '67211471ef8c4cf8f3006e8d', '67ec0bbb7669e0088a063e06', '67d8096bb9460aff580ea201', '67697f83c2839a8ce0044f15', '67ec0bbb7669e0088a063e01', '66c84a4d81896153cf090758', '67694ba59086600ce200cb9a', '6721146032b39c15d70607bd', '6764079b159bc702f408b4f8', '6721147886950846bd0a67b2', '66feb91b80878f512202aa67', '681a2da7b38f6e4fe00e80e9', '67f390889d2cda827d0771bc', '680903dad03f6ba5d90735ce', '67ae52d039bbf51a6108472b', '67f2988c3b6254138a0fb4d6', '67e6c125e62087457b0b72d7', '66f1ba851be5dd53b50080fd', '66e84e1d8a81e313f30591ec', '66bb15ecc9f94c750d035c93', '67ec0bbb7669e0088a063e11', '67c082f8b2fa477a9e0d7248', '66e84cfa93210a899f0a5735', '670e2cb6c9be1337f403194d', '67ec0bbb7669e0088a063e08', '66a0e3d1ffbc408be803f5c9', '66f5bbe414d3fffe92073cdb', '6694f5a3919746067d00ab14', '67fdae7ed9962b438e03407d', '67ae2899d92c82a3ed0c50de', '67ec0bbb7669e0088a063e04', '681b2ed09ab92f1e720fbdbe', '66ce083f5c5f5b121b0290f2', '6694f697d25266d2f009e339', '682ddca570055ec9ff0f7b7e', '6694faff0c3b83b17508c837', '67e6c127e62087457b0b7343', '67e6c125e62087457b0b7306', '6697662311a729843e0f1a4c', '6731c1d137770bc695046694', '66a0e4c39fd91f275a02a6e4', '67e6c120e62087457b0b71bf', '66a0e67a0420abbc440ebc50', '67ae289ad92c82a3ed0c50fb', '681a2d1067f8397a510dd203', '67ec0bbc7669e0088a063e19', '67697f83c2839a8ce0044f19', '67ec0bbb7669e0088a063e0b', '672e0754353a5a0b120b0595', '675976a014fd5d9ff3099f9e', '6694febb64ba6319900bcdcf', '67ec0bbc7669e0088a063e16', '66a36b5e353f9a6e230741cd', '66b1c56be231894bc605699c', '682de429919ab2a6d20c57fc', '66c1f8527bfaa632550308ea', '66a773a9c9540da9fb049d33', '6694f7811cbbbbcbc5094183', '67a4a4aed4061768c803dcf5', '67697f83c2839a8ce0044f12', '66c312da1bf17f39f6007750', '66a0e9697f64bca69b05920a', '67ae289dd92c82a3ed0c51a0', '681a2c72feb0849afe008911', '67ec0bbc7669e0088a063e15', '683575de39dbb7f30d083f3c', '675976a014fd5d9ff3099fa0', '67ae2898d92c82a3ed0c5084', '67ec0bbc7669e0088a063e13', '6745f0a78c31a49e9d0db885', '67ec0bbc7669e0088a063e14', '67ec0bbc7669e0088a063e12', '66e2bd131cd2d1b223012658', '67ec0bbb7669e0088a063e0a', '6694f45fc6f6db032502c35b', '67e6c126e62087457b0b7317', '67502bf5000e65cace0d6451', '66a0df36402cde9dc801b668', '6721145f32b39c15d7060784', '66feb991b976fd3e2f0ef116', '679aa945082f148e4508e16f', '67ae289bd92c82a3ed0c5128', '67ec0bbb7669e0088a063e10', '67ec0bbb7669e0088a063e07', '66b0bac9a4122766860d9e95', '67ae289ed92c82a3ed0c51ed', '67ec0bbb7669e0088a063e0c', '66a0e0e37ec38b51880c027b', '6707e43bed50791cee027917', '6733ea11a30a7604a607f912', '673f6f6dcc71f7ca2f0c09a4', '66e8514389807baee40f4181', '681a2b9d72087ede8207aaa9', '68406039a45b6b52830fb808', '67f38dda58148df2f80975db', '67ec0bbc7669e0088a063e17', '67ec0bbc7669e0088a063e18', '675976a114fd5d9ff3099fa6', '66a0e8ca40ea5eeb67049b1b', '66a0ec13849fe6002707f4a3', '6694f881e793fd466106a51f', '67ec0bbb7669e0088a063e0d', '67ae2899d92c82a3ed0c50cd', '67ae289bd92c82a3ed0c5152', '67e6c121e62087457b0b721c', '66b7565d1660aa389d0a81d2', '6694f924d7d911379105f312', '67a0d1b0f5200d2a3e04327c', '67e6c129e62087457b0b73e1', '67e6c124e62087457b0b72a6', '66fb2da289edca94430def38', '66fb56d39422da15ac02cc37', '67e6c127e62087457b0b7365', '67e6c127e62087457b0b7354', '67ae50a16a1f1341c506ffea', '66e847b73d472776500be8b2', '681a2d5b53d8e2135b0bad37', '67697f83c2839a8ce0044f0c', '66e84d8f1ded8b04ed043ceb', '66bf5ef731a8f1044a0b869b', '67fdb327a3b743d1370e6731', '6737dee4a3f18b3f940bf8e1', '67c0815c35e81086210cf2ab', '66a0e786e0411bfdd00ed692', '6733e62a3c363f4fcf006a8c', '681a549fbc59f56fc501132d', '67be15a371730ffc8e081860'}}

EXPANSION MRR

In [335]:
# DEFINITION:
# Monthly Recurring Revenue gained due to upgrades on a given month

# FORMULA:
# [ Expansion MRR = Num. Monthly Upgrades * Extra Revenue per Subscription ]

# SOURCE / PROCESS FOR CREATING:
# Taken directly from Chartmogul's Metrics Table

CONTRACTION MRR

In [336]:
# DEFINITION:
# Monthly Recurring Revenue lost due to downgrades (and churns?) on a given month

# FORMULA:
# [ Contraction MRR = Num. Monthly Downgrades * Lost Revenue per Subscription ]

# SOURCE / PROCESS FOR CREATING:
# Taken directly from Chartmogul's Metrics Table

CHURNED MRR

In [337]:
# DEFINITION:
# Monthly Recurring Revenue lost due to Customers Churned on a given month

# FORMULA:
# [ Churned MRR = Num. Lost Customers that month * Revenue Lost per Subscription ]

# SOURCE / PROCESS FOR CREATING:
# Taken directly from Chartmogul's Metrics Table

NEW MRR

In [338]:
# DEFINITION:
# Monthly Recurring Revenue gained due to new customers on a given month

# FORMULA:
# [ MRR = Num. New Customers that month * Extra Revenue per Subscription ]

# SOURCE / PROCESS FOR CREATING:
# Taken directly from Chartmogul's Metrics Table

NET NEW MRR

In [339]:
# DEFINITION:
# Net result of MRR fluctuations factoring in upgrades, downgrades, churn and new business. 

# FORMULA:
# [ Net New MRR = New MRR + Expansion MRR - Contraction MRR - Churned MRR ]

# SOURCE / PROCESS FOR CREATING:
# Calculated by adding the metrics above.

ARR

In [340]:
# DEFINITION:
# Annual Recurring Revenue - Calculated by multiplying this month's MRR by twelve.

# FORMULA:
# ARR = MRR * 12

# SOURCE / PROCESS FOR CREATING:
# Taken directly from Chartmogul's Metrics Table

ARPA

In [341]:
# DEFINITION:
# Average Revenue Per Account - How much revenue does each account/customer generate every month on average

# FORMULA:
# ARPA = MRR / Active Customers

# SOURCE / PROCESS FOR CREATING:
# Taken directly from Chartmogul's Metrics Table

CUSTOMER CHURN RATE

In [342]:
# DEFINITION:
# Number of Customers who cancelled their subscription this month 

# SOURCE / PROCESS FOR CREATING:
# Taken directly from Chartmogul's Metrics Table

REVENUE CHURN RATE

In [343]:
# DEFINITION:
# The rate or percentage of Monthly Revenue that is lost this month due to Churn

# FORMULA:
# Revenue Churn Rate = (Churned MRR this Month / MRR Previous Month) × 100

# SOURCE / PROCESS FOR CREATING:
# Calculated from existing metrics which are taken directly from Chartmogul's Metrics Table

LTV

In [344]:
# DEFINITION:
# Customer Lifetime Value - The amount of Revenue generated by the average customer over the course of their time as customers

# FORMULA:
# LTV = ARPA / (Customer Churn Rate / 100)

# SOURCE / PROCESS FOR CREATING:
# Calculated from existing metrics which are taken directly from Chartmogul's Metrics Table

CAC

In [345]:
# DEFINITION:
# Customer Acquisition Cost - The average cost of acquiring a customer

# FORMULA:
# CAC = (Total Sales + Marketing Costs) / Number of New Customers
# Or in this case:
# CAC = CAC Costs (tagged in Contacts Table) / Number of New Customers

# SOURCE / PROCESS FOR CREATING:
# Calculated from existing metrics which are taken directly from Chartmogul's Metrics Table

In [346]:
import pandas as pd

# --- First method: From Holded Invoices (first invoice date) ---

df_HD_invoices_clean['date'] = pd.to_datetime(df_HD_invoices_clean['date'], errors='coerce')


# Get first invoice date per contact
df_first_invoice = (
    df_HD_invoices_clean.sort_values(by='date')
    .drop_duplicates(subset='contact', keep='first')
    .assign(month=lambda df: df['date'].dt.to_period('M').astype(str))
    .groupby('month')['contact']
    .nunique()
    .reset_index(name='new_customers_first_invoice')
)

# --- Second method: From ChartMogul Customers ('customer-since') ---
df_CM_customers_clean['customer-since'] = pd.to_datetime(df_CM_customers_clean['customer-since'], errors='coerce')

# Remove leads (null 'customer-since')
df_cm_customers = df_CM_customers_clean[df_CM_customers_clean['customer-since'].notna()]

# Get month of customer acquisition
df_new_cm = (
    df_cm_customers
    .assign(month=lambda df: df['customer-since'].dt.to_period('M').astype(str))
    .groupby('month')
    .size()
    .reset_index(name='new_customers_customer_since')
)

# --- Merge both results ---
df_new_customers_comparison = pd.merge(
    df_first_invoice,
    df_new_cm,
    on='month',
    how='outer'
).fillna(0).sort_values('month')

df_new_customers_comparison

C:\Users\r_tho\AppData\Local\Temp\ipykernel_19276\231193858.py:27: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  .assign(month=lambda df: df['customer-since'].dt.to_period('M').astype(str))

      month  new_customers_first_invoice  new_customers_customer_since
0   2024-04                          1.0                           6.0
1   2024-05                          0.0                           4.0
2   2024-06                          0.0                           3.0
3   2024-07                          1.0                           5.0
4   2024-08                         18.0                           0.0
5   2024-09                         10.0                           8.0
6   2024-10                        280.0                          11.0
7   2024-11                        136.0                           6.0
8   2024-12                          9.0                           7.0
9   2025-01                         15.0                           3.0
10  2025-02                         18.0                          12.0
11  2025-03                         26.0                          23.0
12  2025-04                          7.0                           8.0
13  2025-05                         16.0                          10.0
14  2025-06                         17.0                          10.0
15  2025-07                          0.0                          12.0

In [372]:
df_HD_purchases_clean['currency'].value_counts()

currency
eur    410
usd     34
aud      3
Name: count, dtype: int64

In [387]:
df_HD_purchases_clean.head(1)

,id,contact,contactName,desc,date,dueDate,multipledueDate,forecastDate,notes,tags,products,tax,subtotal,discount,total,language,status,customFields,docNumber,currency,currencyChange,paymentsTotal,paymentsPending,paymentsRefunds,paymentsDetail,multipledueDate.date,multipledueDate.amount,from.id,from.docType
0,68879a1adaa2fae9720ca5cc,6694faff0c3b83b17508c837,Ignacio Gaminde (Ignacio Gaminde),Fra. A -16-2025 Ignacio Gaminde,2025-07-27 22:00:00,NaN,[],NaN,NaN,"['cac', 'sale', 'staffing']","[{'name': 'Fra. A -16-2025 Ignacio Gaminde', '...",612.5,2916.67,0,3529.17,es,0,[],A -16-2025,eur,1.0,0.0,3529.17,0,NaN,NaN,NaN,NaN,NaN

In [373]:
df_HD_invoices_clean['currency'].value_counts()

currency
eur    1111
Name: count, dtype: int64

In [375]:
df_HD_invoices_clean.columns

Index(['id', 'contact', 'contactName', 'desc', 'date', 'dueDate',
       'multipledueDate', 'forecastDate', 'notes', 'tags', 'products', 'tax',
       'subtotal', 'discount', 'total', 'language', 'status', 'customFields',
       'docNumber', 'currency', 'currencyChange', 'paymentsDetail',
       'paymentsTotal', 'paymentsPending', 'paymentsRefunds', 'shipping',
       'paymentMethodId', 'multipledueDate.date', 'multipledueDate.amount'],
      dtype='object')

In [377]:
len(df_HD_invoices_clean)

1111

In [376]:
df_HD_invoices_clean['currency'].value_counts()

currency
eur    1111
Name: count, dtype: int64

In [384]:
df_HD_payments_clean[(df_HD_payments_clean['amount']>0) & (df_HD_payments_clean['contactName'].isna())]['desc'].value_counts()

desc
TRANSFERENCIA DE STRIPE, CONCEPTO STRIPE.                                                                                                                                              232
STRIPE PAYOUT                                                                                                                                                                           15
Exchanged To Usd Main                                                                                                                                                                   14
Payment From Komboai Technologies Sl                                                                                                                                                     4
Paddle.net* Netnut Ltd                                                                                                                                                                   3
GESTION DEVOLUCIONES - INTERIOR BS                                                                                                                                                       3
Apollo.io                                                                                                                                                                                2
Bettercontact                                                                                                                                                                            2
Payment From Stripe Technology Europe Ltd                                                                                                                                                2
Refund From Elementor                                                                                                                                                                    2
RETROCESION DE COMISIONES Y GASTOS                                                                                                                                                       2
Heyreach                                                                                                                                                                                 1
TRANSFERENCIA A FAVOR DE Paraforma Pty Ltd, REFERENCIA: 0049 1896 696 0181832                                                                                                            1
Lovable                                                                                                                                                                                  1
TRANSFERENCIA INMEDIATA A FAVOR DE Komboai Technologies S.l. CONCEPTO interno                                                                                                            1
TRANSFERENCIA INMEDIATA DE AIRWALLEX (UK) LIMITED, CONCEPTO pay B0WHY1jERDWdRL                                                                                                           1
TRANSFERENCIA DE Trade Republic Bank GmbH, CONCEPTO No hemos podido procesar tu deposito. RI-3fbb7198868b46ae9c31f68e61d2c7b7 NOT PROVIDED Trade Republic Bank GmbH referidos.           1
TRANSFERENCIA DE DEVOLUCIONES TRIBUTARIAS, AGENCIA ESTATAL DE ADMIN, CONCEPTO AEAT APL:IVA AUTOLIQUIDACION 24MOD:303INF:EXPEDIENTE AGENCIA TRIBUTARIA EXP:2024DEV30383400026A AEAT.      1
TRANSFERENCIA A FAVOR DE KomboAI Technologies SL CONCEPTO: interna                                                                                                                       1
Refund From Notion Labs, Inc.                                                                                                                                                            1
TRANSFERENCIA DE ANDREA DIODORO, CONCEPTO IRPF.                                                                                                                                          1
TRANSFERENCIA DE ENISA, CONCEPTO Fact:0000013532-.                                                                                                                                       1
regul.                                                                                                                                                                                   1
TRANSFERENCIA DE Stripe Technology Europe Ltd, CONCEPTO STRIPE U8U8B2.                                                                                                                   1
2605-1919, Subscription creation                                                                                                                                                         1
Subscription update                                                                                                                                                                      1
2762-6770, Subscription update                                                                                                                                                           1
TRANSFERENCIA A FAVOR DE KomboAI Technologies SL CONCEPTO: transfer interno                                                                                                              1
Cursor, Ai Powered Ide                                                                                                                                                                   1
Restaurante Casa Julio                                                                                                                                                                   1
amp.cap. Jared Gil Ruiz                                                                                                                                                                  1
amp.cap. Tech Hub Iberia SL                                                                                                                                                              1
amp.cap. Charles Simonetti                                                                                                                                                               1
amp.cap. Desarrollo, Viabilidad y Sonestibilidad SL                                                                                                                                      1
amp.cap. N Ventures 1 Incubacion FCRE                                                                                                                                                    1
amp.cap. Eoniq Mediterranean Seed Fund I FCRE SA                                                                                                                                         1
amp.cap. Think Bigger Fund I FCRE                                                                                                                                                        1
amp.cap. Stéphane Roy                                                                                                                                                                    1
TRANSFERENCIA A FAVOR DE Komboai Technologies CONCEPTO: transfer interno                                                                                                                 1
From Alessandro Pintaudi                                                                                                                                                                 1
TRANSFERENCIA DE EONIQ MEDITERRANEAN SEED FUND I FCRE, CONCEPTO AMPLIACION DE CAPITAL.                                                                                                   1
TRANSFERENCIA A FAVOR DE N VENTURES 1 INCUBACION F.C.R.E. CONCEPTO: devolucion transferencia por error                                                                                   1
TRANSFERENCIA DE ROGER SINDREU ABELLO, CONCEPTO Aportacion Roger Sindreu Abello.                                                                                                         1
TRANSFERENCIA DE N VENTURES 1 INCUBACION F.C.R.E., CONCEPTO Aportacion N VENTURES 1 INCUBACION FCRE.                                                                                     1
Club Natacio Atl Barce                                                                                                                                                                   1
amp.cap. Roger Sindreu Abello                                                                                                                                                            1
clientes stripe                                                                                                                                                                          1
TRANSFERENCIA DE THINK BIGGER FUND I FCRE, CONCEPTO INVERSION THINK BIGGER FUND I.                                                                                                       1
Exchanged To Aud                                                                                                                                                                         1
Payment From Komboai Technologies S.l.                                                                                                                                                   1
TRANSFERENCIA DE CHARLES SIMONETTI, CONCEPTO Aportacion Charles Simonetti.                                                                                                               1
TRANSFERENCIA DE S.M.J. Roy, CONCEPTO Aportacion Stephane Roy                                                                                                                            1
TRANSFERENCIA DE DESARROLLO VIABILIDAD Y SOSTENIBILIDAD S.L., CONCEPTO Aportacion Desarrollo, Viabilidad Y Sostenibilidad, S.L..                                                         1
TRANSFERENCIA DE TECH HUB IBERIA SL, CONCEPTO Aportacion TECH HUB IBERIA.                                                                                                                1
Transferencia komboai technologies sl- DocNum:20240417001232239664                                                                                                                       1
TRANSFERENCIA DE JARED GIL RUIZ, CONCEPTO APORTACION JARED GIL RUIZ.                                                                                                                     1
TRANSFERENCIA DE ANZBAU09, REFERENCIA: 0049 5494 696 2HXNQ91 CONCEPTO /ROC/NOTPROVIDED                                                                                                   1
RECIBO MONDAY BY URBANIA 3, S.L. 20240212/EUR 445.28/2024-04-02 No RECIBO 0049 1896 755 BBDBLMY REF. MANDATO SEPAKOMBO, DE                                                               1
TRANSFERENCIA DE N VENTURES 1 INCUBACION F.C.R.E., CONCEPTO PRESTAMO CONVERTIBLE N VENTURES 1.                                                                                           1
CANCELACION ACRREDORES APORTACIONES DINERARIAS PARA CONSTITUCI 004918966870001488                                                                                                        1
CANCELACION ACRREDORES APORTACIONES DINERARIAS PARA CONSTITUCI 004918966870001486                                                                                                        1
CANCELACION ACRREDORES APORTACIONES DINERARIAS PARA CONSTITUCI 004918966870001487                                                                                                        1
Name: count, dtype: int64

In [ ]:
df_HD_payments_clean[df_HD_payments_clean['amount']>0]

In [385]:
df_HD_purchases_clean.head(1)

,id,contact,contactName,desc,date,dueDate,multipledueDate,forecastDate,notes,tags,products,tax,subtotal,discount,total,language,status,customFields,docNumber,currency,currencyChange,paymentsTotal,paymentsPending,paymentsRefunds,paymentsDetail,multipledueDate.date,multipledueDate.amount,from.id,from.docType
0,68879a1adaa2fae9720ca5cc,6694faff0c3b83b17508c837,Ignacio Gaminde (Ignacio Gaminde),Fra. A -16-2025 Ignacio Gaminde,2025-07-27 22:00:00,NaN,[],NaN,NaN,"['cac', 'sale', 'staffing']","[{'name': 'Fra. A -16-2025 Ignacio Gaminde', '...",612.5,2916.67,0,3529.17,es,0,[],A -16-2025,eur,1.0,0.0,3529.17,0,NaN,NaN,NaN,NaN,NaN

In [386]:
df_HD_purchases_clean[(df_HD_purchases_clean['total'].isna()) | (df_HD_purchases_clean['contact'].isna())]

Empty DataFrame
Columns: [id, contact, contactName, desc, date, dueDate, multipledueDate, forecastDate, notes, tags, products, tax, subtotal, discount, total, language, status, customFields, docNumber, currency, currencyChange, paymentsTotal, paymentsPending, paymentsRefunds, paymentsDetail, multipledueDate.date, multipledueDate.amount, from.id, from.docType]
Index: []

In [371]:
foreign_purchases = df_HD_purchases_clean[df_HD_purchases_clean['currency']!= "eur"]
foreign_purchases

,id,contact,contactName,desc,date,dueDate,multipledueDate,forecastDate,notes,tags,products,tax,subtotal,discount,total,language,status,customFields,docNumber,currency,currencyChange,paymentsTotal,paymentsPending,paymentsRefunds,paymentsDetail,multipledueDate.date,multipledueDate.amount,from.id,from.docType
1,688875f3ffd340ef55006bfa,6694f7811cbbbbcbc5094183,Paraforma Pty Ltd (Paraforma Pty Ltd),Fra. INV-0045 Paraforma Pty Ltd,2025-07-27 22:00:00,NaN,[],NaN,NaN,"['moneda', 'opex', 'prod', 'staffing']","[{'name': 'Fra. INV-0045 Paraforma Pty Ltd', '...",0.0,2080.75,0,2080.75,NaN,0,[],INV-0045,aud,1.775915,0.00,2.080750e+03,0,NaN,NaN,NaN,NaN,NaN
2,6888742d0e25ae0cd5041e87,6694f881e793fd466106a51f,Paddle.com Market Ltd (Paddle.com Market Ltd),Fra. 790-17369 Paddle.com Market Ltd,2025-07-26 22:00:00,NaN,[],NaN,NaN,"['cogs', 'moneda', 'tech', 'tool']",[{'name': 'Fra. 790-17369 Paddle.com Market Lt...,0.0,23.31,0,23.31,NaN,0,[],790-17369,usd,1.158252,0.00,2.331000e+01,0,NaN,NaN,NaN,NaN,NaN
6,687fa31496f9c9f27709c60f,680903dad03f6ba5d90735ce,ChartMogul GmbH & Co. KG (ChartMogul GmbH & Co...,Fra. 106641 ChartMogul GmbH & Co. KG,2025-07-21 22:00:00,NaN,[],NaN,NaN,"['opex', 'ops', 'tool']",[{'name': 'Fra. 106641 ChartMogul GmbH & Co. K...,0.0,101.78,0,101.78,NaN,1,[],106641,usd,1.169153,101.78,0.000000e+00,0,"[{'id': '68837630d27719cf1d0c8503', 'amount': ...",NaN,NaN,NaN,NaN
8,687e383f30f407b34502376c,66a0e85b1951a0a871019577,"SerpApi, LLC (SerpApi, LLC)","Fra. 1CD72209-0026 SerpApi, LLC",2025-07-20 22:00:00,NaN,[],NaN,NaN,"['cogs', 'tech', 'tool']","[{'name': 'Fra. 1CD72209-0026 SerpApi, LLC', '...",0.0,64.49,0,64.49,NaN,1,[],1CD72209-0026,usd,1.162899,64.49,0.000000e+00,0,"[{'id': '68837633b86813c24800bc36', 'amount': ...",NaN,NaN,NaN,NaN
10,687df3a1bbc946d8be0575ff,67be15a371730ffc8e081860,ZenLeads Inc. (ZenLeads Inc.),Fra. 024C0FA6-0012 ZenLeads Inc.,2025-07-19 22:00:00,NaN,[],NaN,NaN,"['cogs', 'tech', 'tool']","[{'name': 'Fra. 024C0FA6-0012 ZenLeads Inc.', ...",0.0,10.32,0,10.32,NaN,1,[],024C0FA6-0012,usd,1.162899,10.32,0.000000e+00,0,"[{'id': '68837637ae9fdb433507c1fe', 'amount': ...",NaN,NaN,NaN,NaN
11,687e14b842c64e61cc0a5893,681b2ed09ab92f1e720fbdbe,Lovable Labs Incorporated (Lovable Labs Incorp...,Fra. 9E97B890-0004 Lovable Labs Incorporated,2025-07-19 22:00:00,NaN,[],NaN,NaN,"['cogs', 'tech', 'tool']",[{'name': 'Fra. 9E97B890-0004 Lovable Labs Inc...,0.0,21.50,0,21.50,NaN,1,[],9E97B890-0004,usd,1.162899,21.50,0.000000e+00,0,"[{'id': '68837634917bf4f252067619', 'amount': ...",NaN,NaN,NaN,NaN
12,6879f53ccec1deb67c0d38d3,67ae52d039bbf51a6108472b,Cognism Ltd (Cognism Ltd),Fra. INV-149685 Cognism Ltd,2025-07-16 22:00:00,NaN,[],NaN,NaN,"['cogs', 'tech', 'tool']","[{'name': 'Fra. INV-149685 Cognism Ltd', 'desc...",0.0,860.55,0,860.55,NaN,1,[],INV-149685,usd,1.162048,860.55,0.000000e+00,0,"[{'id': '68837639709511006c079cb0', 'amount': ...",NaN,NaN,NaN,NaN
13,687755e8b710f8c178097ad6,681a5579f1ea6b91650b2f65,BetterContact (BetterContact),Fra. 3EB2B17E-6827 BetterContact,2025-07-15 22:00:00,NaN,[],NaN,NaN,"['cogs', 'tech', 'tool']","[{'name': 'Fra. 3EB2B17E-6827 BetterContact', ...",0.0,955.48,0,955.48,NaN,1,[],3EB2B17E-6827,usd,1.161926,955.48,0.000000e+00,0,"[{'id': '688393ecac075aa2a50b6c95', 'amount': ...",NaN,NaN,NaN,NaN
14,6878b9f25cbbd8bc150f7755,6694f881e793fd466106a51f,Paddle.com Market Ltd (Paddle.com Market Ltd),Fra. 790-17230 Paddle.com Market Ltd,2025-07-15 22:00:00,NaN,[],NaN,NaN,"['cogs', 'tech', 'tool']",[{'name': 'Fra. 790-17230 Paddle.com Market Lt...,0.0,516.23,0,516.23,NaN,1,[],790-17230,usd,1.162277,516.23,0.000000e+00,0,"[{'id': '68837646071fa27c1f03ceb2', 'amount': ...",NaN,NaN,NaN,NaN
17,6877560f230d5abc180f9027,681a5579f1ea6b91650b2f65,BetterContact (BetterContact),Fra. 3EB2B17E-6816 BetterContact,2025-07-14 22:00:00,NaN,[],NaN,NaN,"['cogs', 'tech', 'tool']","[{'name': 'Fra. 3EB2B17E-6816 BetterContact', ...",0.0,223.77,0,223.77,NaN,1,[],3EB2B17E-6816,usd,1.161926,223.77,0.000000e+00,0,"[{'id': '68839411f67c5dc4c9015d6a', 'amount': ...",NaN,NaN,NaN,NaN
20,6870dad7298c43b2a80d0a65,67be15a371730ffc8e081860,ZenLeads Inc. (ZenLeads Inc.),Fra. YNFE2AMJ-0011 ZenLeads Inc.,2025-07-10 22:00:00,NaN,[],NaN,NaN,[],"[{'name': 'Fra. YNFE2AMJ-0011 ZenLeads Inc.', ...",0.0,254.41,0,254.41,NaN,1,[],YNFE2AMJ-0011,usd,1.167413,254.41,0.000000e+00,0,"[{'id': '6883955fc435cda9060e3d9c', 'amount': ...",NaN,NaN,NaN,NaN
22,686f9d91ac4a87122c029343,686f9d2da3972b9b98032aff,CloudTalk S. Γ. O. (CloudTalk S. Γ. O.),Fra. 25014245 CloudTalk S. Γ. O.,2025-07-07 22:00:00,NaN,[],NaN,NaN,[],"[{'name': 'Fra. 25014245 CloudTalk S. Γ. O.', ...",0.0,17.04,0,17.04,NaN,1,[],25014245,usd,1.173489,17.04,0.000000e+00,0,"[{'id': '68836542313f10285c00fad1', 'amount': ...",NaN,NaN,NaN,NaN
23,686b7effcef17d44ef073c52,6694f881e793fd466106a51f,Paddle.com Market Ltd (Paddle.com Market Ltd),Fra. 790-17050 Paddle.com Market Ltd,2025-07-05 22:00:00,NaN,[],NaN,NaN,[],[{'name': 'Fra. 790-17050 Paddle.com Market Lt...,0.0,278.75,0,278.75,NaN,1,[],790-17050,usd,1.176678,278.75,0.000000e+00,0,"[{'id': '688395755db6d1daf50be10b', 'amount': ...",NaN,NaN,NaN,NaN
24,6867a5d2b3f63f45ae015c18,679aa945082f148e4508e16f,Deeptrace Inc. (Deeptrace Inc.),Fra. 25365C73-0004 Deeptrace Inc.,2025-07-02 22:00:00,NaN,[],NaN,NaN,[],"[{'name': 'Fra. 25365C73-0004 Deeptrace Inc.',...",0.0,424.49,0,424.49,NaN,1,[],25365C73-0004,usd,1.177881,424.49,0.000000e+00,0,"[{'id': '686807f7f5c7d4b88d0df1fe', 'amount': ...",NaN,NaN,NaN,NaN
27,688332ffa52bbdbeef09f178,6694f881e793fd466106a51f,Paddle.com Market Ltd (Paddle.com Market Ltd),Fra. 790-15436 Paddle.com Market Ltd,2025-06-30 22:00:00,NaN,[],NaN,NaN,"['abril', 'cogs', 'tech', 'tool']",[{'name': 'Fra. 790-15436 Paddle.com Market Lt...,0.0,304.91,0,304.91,NaN,0,[],790-15436,usd,1.174126,0.00,3.049100e+02,0,NaN,NaN,NaN,NaN,NaN
28,68639b56c204471eab03a126,67be15a371730ffc8e081860,ZenLeads Inc. (ZenLeads Inc.),Fra. YNFE2AMJ-0009 ZenLeads Inc.,2025-06-29 22:00:00,NaN,[],NaN,NaN,[],"[{'name': 'Fra. YNFE2AMJ-0009 ZenLeads Inc.', ...",0.0,30.68,0,30.68,NaN,1,[],YNFE2AMJ-0009,usd,1.178481,30.68,0.000000e+00,0,"[{'id': '6863fc5fdacdb26330089512', 'amount': ...",NaN,NaN,NaN,NaN
32,68639c006415e3673d0e7a24,67be15a371730ffc8e081860,ZenLeads Inc. (ZenLeads Inc.),Fra. YNFE2AMJ-0008 ZenLeads Inc.,2025-06-26 22:00:00,NaN,[],NaN,NaN,[],"[{'name': 'Fra. YNFE2AMJ-0008 ZenLeads Inc.', ...",0.0,38.86,0,38.86,NaN,1,[],YNFE2AMJ-0008,usd,1.178481,38.86,0.000000e+00,0,"[{'id': '6863fc63bb756e25510a06f9', 'amount': ...",NaN,NaN,NaN,NaN
35,68639e2fbeccef34f90eac39,6694f7811cbbbbcbc5094183,Paraforma Pty Ltd (Paraforma Pty Ltd),Fra. INV-0043 Paraforma Pty Ltd,2025-06-25 22:00:00,NaN,[],NaN,NaN,[],"[{'name': 'Fra. INV-0043 Paraforma Pty Ltd', '...",0.0,2065.51,0,2065.51,NaN,1,[],INV-0043,aud,1.793035,2065.51,0.000000e+00,0,"[{'id': '6883611586a549100402690e', 'amount': ...",NaN,NaN,NaN,NaN
39,685cfde8971038e2c600a543,6694f881e793fd466106a51f,Paddle.com Market Ltd (Paddle.com Market Ltd),Fra. 790-16861 Paddle.com Market Ltd,2025-06-24 22:00:00,NaN,[],NaN,NaN,[],[{'name': 'Fra. 790-16861 Paddle.com Market Lt...,0.0,23.11,0,23.11,NaN,1,[],790-16861,usd,1.168115,23.11,0.000000e+00,0,"[{'id': '6863fc66da82eafbea06e372', 'amount': ...",NaN,NaN,NaN,NaN
45,68596db305df4434df076ab6,67be15a371730ffc8e081860,ZenLeads Inc. (ZenLeads Inc.),Fra. 024COFA6-0010 ZenLeads Inc.,2025-06-19 22:00:00,NaN,[],NaN,NaN,[],"[{'name': 'Fra. 024COFA6-0010 ZenLeads Inc.', ...",0.0,10.17,0,10.17,NaN,1,[],024COFA6-0010,usd,1.179677,10.41,-2.400000e-01,0,"[{'id': '68596de992260bb1ec0169df', 'amount': ...",NaN,NaN,NaN,NaN
46,6867a4ebc9519f29050d1500,68273d358a011e371c00e1d4,HeyReach Inc OÜ (HeyReach Inc OÜ),Fra. AE522E9A-48575 HeyReach Inc OÜ,2025-06-19 22:00:00,NaN,[],NaN,NaN,[],[{'name': 'Fra. AE522E9A-48575 HeyReach Inc OÜ...,0.0,73.65,0,73.65,NaN,1,[],AE522E9A-48575,usd,1.140789,73.65,0.000000e+00,0,"[{'id': '686807fa5dc5cb4ad001e794', 'amount': ...",NaN,NaN,NaN,NaN
47,6867bad0c739eb35360d7548,681b2ed09ab92f1e720fbdbe,Lovable Labs Incorporated (Lovable Labs Incorp...,Fra. 9E97B890-0003 Lovable Labs Incorporated,2025-06-19 22:00:00,NaN,[],NaN,NaN,[],[{'name': 'Fra. 9E97B890-0003 Lovable Labs Inc...,0.0,21.91,0,21.91,NaN,1,[],9E97B890-0003,usd,1.140789,21.91,0.000000e+00,0,"[{'id': '686807fc5ed3c136470c80a4', 'amount': ...",NaN,NaN,NaN,NaN
51,6867a4a63f4fdce86f073bfa,68273d358a011e371c00e1d4,HeyReach Inc OÜ (HeyReach Inc OÜ),Fra. AE522E9A-47003 HeyReach Inc OÜ,2025-06-13 22:00:00,NaN,[],NaN,NaN,[],[{'name': 'Fra. AE522E9A-47003 HeyReach Inc OÜ...,0.0,296.55,0,296.55,NaN,1,[],AE522E9A-47003,usd,1.177881,296.55,0.000000e+00,0,"[{'id': '686807fefc151495a901603e', 'amount': ...",NaN,NaN,NaN,NaN
55,684960578e267e330c06f79c,67be15a371730ffc8e081860,ZenLeads Inc. (ZenLeads Inc.),Fra. YNFE2AMJ-0003 ZenLeads Inc.,2025-06-10 22:00:00,NaN,[],NaN,NaN,[],"[{'name': 'Fra. YNFE2AMJ-0003 ZenLeads Inc.', ...",0.0,83.92,0,83.92,NaN,1,[],YNFE2AMJ-0003,usd,1.179677,86.71,-2.790000e+00,0,"[{'id': '685960a81ad5c0c9bc045512', 'amount': ...",NaN,NaN,NaN,NaN
56,6867ba249e15496ac6089d5d,673245b7c31b77924705a339,"OpenAI, LLC (OpenAI, LLC)","Fra. 118F6C05-0067 OpenAI, LLC",2025-06-10 22:00:00,NaN,[],NaN,NaN,[],"[{'name': 'Fra. 118F6C05-0067 OpenAI, LLC', 'd...",0.0,83.28,0,83.28,NaN,1,[],118F6C05-0067,usd,1.140789,83.28,0.000000e+00,0,"[{'id': '68680800ac0e29d4240e4f4e', 'amount': ...",NaN,NaN,NaN,NaN
61,6867b1c0c854df5f8507fc13,6733e62a3c363f4fcf006a8c,Cursor (Cursor),Fra. A37D8407-0008 Cursor,2025-06-03 22:00:00,NaN,[],NaN,NaN,[],"[{'name': 'Fra. A37D8407-0008 Cursor', 'desc':...",0.0,17.53,0,17.53,NaN,1,[],A37D8407-0008,usd,1.140789,17.53,0.000000e+00,0,"[{'id': '6868080583eb9f67fb06d53c', 'amount': ...",NaN,NaN,NaN,NaN
65,68405f1dd8f39b13790c8a35,6694f881e793fd466106a51f,Paddle.com Market Ltd (Paddle.com Market Ltd),Fra. 790-16492 Paddle.com Market Ltd,2025-06-02 22:00:00,NaN,[],NaN,NaN,[],[{'name': 'Fra. 790-16492 Paddle.com Market Lt...,0.0,314.98,0,314.98,NaN,1,[],790-16492,usd,1.136570,314.98,5.684342e-14,0,"[{'id': '6883763cc5afec197800df09', 'amount': ...",NaN,NaN,NaN,NaN
86,682ddc288ec7993b1f049672,67be15a371730ffc8e081860,ZenLeads Inc. (ZenLeads Inc.),Fra. 024COFA6-0008 ZenLeads Inc.,2025-05-19 22:00:00,NaN,[],NaN,NaN,[],"[{'name': 'Fra. 024COFA6-0008 ZenLeads Inc.', ...",0.0,10.17,0,10.17,NaN,1,[],024COFA6-0008,usd,1.179677,10.67,-5.000000e-01,0,"[{'id': '682de7e21d8d9ce9d90ca067', 'amount': ...",NaN,NaN,NaN,NaN
110,6812e35af070dde1dc0a49fb,67be15a371730ffc8e081860,ZenLeads Inc. (ZenLeads Inc.),Fra. YNFE2AMJ-0001 ZenLeads Inc.,2025-04-29 22:00:00,NaN,[],NaN,NaN,[],"[{'name': 'Fra. YNFE2AMJ-0001 ZenLeads Inc.', ...",0.0,83.92,0,83.92,NaN,1,[],YNFE2AMJ-0001,usd,1.179677,87.05,-3.130000e+00,0,"[{'id': '6819ec694771e516f7017af4', 'amount': ...",NaN,NaN,NaN,NaN
122,6806a42fc1e8ba1b3e0e906a,66a0e85b1951a0a871019577,"SerpApi, LLC (SerpApi, LLC)","Fra. 1CD72209-0023 SerpApi, LLC",2025-04-20 22:00:00,NaN,[],NaN,NaN,[],"[{'name': 'Fra. 1CD72209-0023 SerpApi, LLC', '...",0.0,65.95,0,65.95,NaN,1,[],1CD72209-0023,usd,1.137236,65.95,0.000000e+00,0,"[{'id': '6809016858f9123316049fb5', 'amount': ...",NaN,NaN,NaN,NaN
125,6806a55bbb67ffbb980f95fc,67be15a371730ffc8e081860,ZenLeads Inc. (ZenLeads Inc.),Fra. 024COFA6-0006 ZenLeads Inc.,2025-04-19 22:00:00,NaN,[],NaN,NaN,[],"[{'name': 'Fra. 024COFA6-0006 ZenLeads Inc.', ...",0.0,51.88,0,51.88,NaN,1,[],024COFA6-0006,usd,1.137236,51.88,0.000000e+00,0,"[{'id': '68090149aa47e7d58d036501', 'amount': ...",NaN,NaN,NaN,NaN
158,67dd890051ea0718f20d6cd6,66a0e85b1951a0a871019577,"SerpApi, LLC (SerpApi, LLC)","Fra. 1CD72209-0022 SerpApi, LLC",2025-03-20 23:00:00,NaN,[],NaN,NaN,[],"[{'name': 'Fra. 1CD72209-0022 SerpApi, LLC', '...",0.0,69.25,0,69.25,NaN,1,[],1CD72209-0022,usd,1.082989,69.25,0.000000e+00,0,"[{'id': '67eb87eeb88cdf98560a9150', 'amount': ...",NaN,NaN,NaN,NaN
252,676d8a0f724141e66f0fcfc1,66a0e85b1951a0a871019577,"SerpApi, LLC (SerpApi, LLC)","Fra. 1CD72209-0018 SerpApi, LLC",2024-12-24 23:00:00,NaN,[],NaN,NaN,[],"[{'name': 'Fra. 1CD72209-0018 SerpApi, LLC', '...",0.0,72.13,0,72.13,NaN,1,[],1CD72209-0018,usd,1.039831,72.13,0.000000e+00,0,"[{'id': '6773d723a1a9dba1b30eba62', 'amount': ...",NaN,NaN,NaN,NaN
343,66fb2b70adf1099ee50f7774,66a0e85b1951a0a871019577,"SerpApi, LLC (SerpApi, LLC)","Fra. 1CD72209-0015 SerpApi, LLC",2024-09-29 22:00:00,NaN,[],NaN,NaN,[],"[{'name': 'Fra. 1CD72209-0015 SerpApi, LLC', '...",0.0,67.19,0,67.19,NaN,1,[],1CD72209-0015,usd,1.116184,67.19,0.000000e+00,0,"[{'id': '67055d81b3790332e40f3c2c', 'amount': ...",NaN,NaN,NaN,NaN
351,66fb2f1cd906ec0c8803a20b,66fb2da289edca94430def38,Envato Pty Ltd (Envato Pty Ltd),Fra. IVHF34805077 Envato Pty Ltd,2024-09-20 22:00:00,NaN,[],NaN,NaN,[],"[{'name': 'Fra. IVHF34805077 Envato Pty Ltd', ...",0.0,3.25,0,3.25,NaN,1,[],IVHF34805077,usd,1.116184,3.25,0.000000e+00,0,"[{'id': '67056918fe6569b69a08da78', 'amount': ...",NaN,NaN,NaN,NaN
352,66fb562a4c621a84fa0435f6,66fb2da289edca94430def38,Envato Pty Ltd (Envato Pty Ltd),Fra. IVBF53704693 Envato Pty Ltd,2024-09-20 22:00:00,NaN,[],NaN,NaN,[],"[{'name': 'Fra. IVBF53704693 Envato Pty Ltd', ...",0.0,13.22,0,13.22,NaN,1,[],IVBF53704693,usd,1.098599,13.22,0.000000e+00,0,"[{'id': '67056918ba240799d00eece4', 'amount': ...",NaN,NaN,NaN,NaN
368,66d8c4942ab79bfd6e056d05,6694f7811cbbbbcbc5094183,Paraforma Pty Ltd (Paraforma Pty Ltd),Fra. INV-0022 Paraforma Pty Ltd,2024-08-30 22:00:00,NaN,[],NaN,NaN,[],"[{'name': 'Fra. INV-0022 Paraforma Pty Ltd', '...",0.0,640.81,0,640.81,NaN,1,[],INV-0022,aud,1.648230,640.81,0.000000e+00,0,"[{'id': '66e4239e256302e9610fc221', 'amount': ...",NaN,NaN,NaN,NaN

In [370]:
df_HD_purchases_clean.head(1)

,id,contact,contactName,desc,date,dueDate,multipledueDate,forecastDate,notes,tags,products,tax,subtotal,discount,total,language,status,customFields,docNumber,currency,currencyChange,paymentsTotal,paymentsPending,paymentsRefunds,paymentsDetail,multipledueDate.date,multipledueDate.amount,from.id,from.docType
0,68879a1adaa2fae9720ca5cc,6694faff0c3b83b17508c837,Ignacio Gaminde (Ignacio Gaminde),Fra. A -16-2025 Ignacio Gaminde,2025-07-27 22:00:00,NaN,[],NaN,NaN,"['cac', 'sale', 'staffing']","[{'name': 'Fra. A -16-2025 Ignacio Gaminde', '...",612.5,2916.67,0,3529.17,es,0,[],A -16-2025,eur,1.0,0.0,3529.17,0,NaN,NaN,NaN,NaN,NaN

In [369]:
df_HD_invoices_clean.head(1)

,id,contact,contactName,desc,date,dueDate,multipledueDate,forecastDate,notes,tags,products,tax,subtotal,discount,total,language,status,customFields,docNumber,currency,currencyChange,paymentsDetail,paymentsTotal,paymentsPending,paymentsRefunds,shipping,paymentMethodId,multipledueDate.date,multipledueDate.amount
0,68640b2e4d4b9230af022ea8,6852bf0ed7f7b87ec2042a11,MediaEngine Srl,7BE139D9-5817,2025-06-29 22:00:00,NaN,[],NaN,NaN,[],"[{'name': '', 'desc': '', 'price': 99.83, 'uni...",0.0,99.83,0.0,99.83,es,1,[],F250383,eur,1,"[{'id': '6864fa8a1192b29d9d0c2745', 'amount': ...",99.83,0.0,0.0,NaN,NaN,NaN,NaN

In [367]:
df_HD_payments_clean.head(1)

,id,bankId,contactId,contactName,amount,desc,date,change,documentType,documentId
0,688375402f5c9baf800ce037,6697ee29ecc2d0d7aa0e0db4,66a0df36402cde9dc801b668,Slack Technologies Limited,-63.53,Compra SBIE-9184465 Fra. SBIE-9184465 Slack Te...,2025-07-25 00:00:00,NaN,trans,688374724c3f93c8740102cf

In [366]:
df_CM_mrr_components_clean.head(1)

,date,mrr,percentage-change,mrr-new-business,mrr-expansion,mrr-contraction,mrr-churn,mrr-reactivation
0,2024-03-31,0,0.0,0,0,0,0,0

In [364]:
df_HD_purchases_clean.head(1)

,id,contact,contactName,desc,date,dueDate,multipledueDate,forecastDate,notes,tags,products,tax,subtotal,discount,total,language,status,customFields,docNumber,currency,currencyChange,paymentsTotal,paymentsPending,paymentsRefunds,paymentsDetail,multipledueDate.date,multipledueDate.amount,from.id,from.docType
0,68879a1adaa2fae9720ca5cc,6694faff0c3b83b17508c837,Ignacio Gaminde (Ignacio Gaminde),Fra. A -16-2025 Ignacio Gaminde,2025-07-27 22:00:00,NaN,[],NaN,NaN,"['cac', 'sale', 'staffing']","[{'name': 'Fra. A -16-2025 Ignacio Gaminde', '...",612.5,2916.67,0,3529.17,es,0,[],A -16-2025,eur,1.0,0.0,3529.17,0,NaN,NaN,NaN,NaN,NaN

In [365]:
df_HD_purchases_clean['status'].value_counts()

status
1    441
0      6
Name: count, dtype: int64

CAC:LTV

OPEX

COGS

FINANCIAL COSTS

EBITDA

BURN RATE

RUNWAY

In [347]:
df_CM_metrics_clean.head(5)

,date,mrr,mrr-percentage-change,arr,arr-percentage-change,customer-churn-rate,customer-churn-rate-percentage-change,mrr-churn-rate,mrr-churn-rate-percentage-change,ltv,ltv-percentage-change,customers,customers-percentage-change,asp,asp-percentage-change,arpa,arpa-percentage-change,year,month,month_start
0,2024-03-31,0,0.0,0,0.0,0.00,0.0,0.00,0.0,0,0.0,0,0.0,0,0.0,0,0.0,2024,3,2024-03-01
1,2024-04-30,27900,0.0,334800,0.0,0.00,0.0,0.00,0.0,0,0.0,6,0.0,4650,0.0,4650,0.0,2024,4,2024-04-01
2,2024-05-31,56400,0.0,676800,0.0,0.00,0.0,-17.56,0.0,0,0.0,10,0.0,5900,0.0,5640,0.0,2024,5,2024-05-01
3,2024-06-30,75500,0.0,906000,0.0,0.00,0.0,12.23,0.0,0,0.0,13,0.0,8667,0.0,5807,0.0,2024,6,2024-06-01
4,2024-07-31,153728,0.0,1844736,0.0,15.38,0.0,-10.26,0.0,0,0.0,16,0.0,14096,0.0,9608,0.0,2024,7,2024-07-01

In [348]:
df_CM_customers_clean.head(5)

,id,uuid,external_id,name,email,status,customer-since,data_source_uuid,data_source_uuids,external_ids,company,country,state,city,zip,lead_created_at,free_trial_started_at,mrr,arr,billing-system-url,chartmogul-url,billing-system-type,currency,currency-sign,owner,website_url,attributes.tags,address.country,address.state,address.city,address.address_zip,attributes.hubspot.Company_owner,attributes.hubspot.Lifecycle_Stage,attributes.hubspot.Latest_Source,attributes.hubspot.Original_Source,attributes.stripe.userId,attributes.stripe.companyId,attributes.hubspot.Industry,attributes.hubspot.Time_Last_Seen,attributes.hubspot.Type
0,177867729,cus_9a55ecba-bcdc-4d19-89d1-05ddfac08906,cus_PubGEWYD0zJS7r,Edicom Capital,lgalceran@edicom.es,Active,2024-04-12 15:30:48+00:00,ds_78983044-48ff-11ef-a3c9-aba08b7ca782,['ds_78983044-48ff-11ef-a3c9-aba08b7ca782'],['cus_PubGEWYD0zJS7r'],NaN,ES,NaN,Paterna,46980,NaN,NaN,30135,361620,https://dashboard.stripe.com/customers/cus_Pub...,https://app.chartmogul.com/#/customers/1778677...,Stripe,EUR,€,NaN,https://edicom.es,[],Spain,NaN,Paterna,46980,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,177867728,cus_60c6c415-10dd-485f-ad9c-60708596de49,cus_Pw72IlNTuidXmn,Antonio Manuel Espín Martín,amespin@kodopeople.com,Cancelled,2024-04-16 16:24:29+00:00,ds_78983044-48ff-11ef-a3c9-aba08b7ca782,"['ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c', 'd...","['6946177521', 'cus_Pw72IlNTuidXmn']",NaN,ES,NaN,Granada,18016,NaN,NaN,0,0,https://dashboard.stripe.com/customers/cus_Pw7...,https://app.chartmogul.com/#/customers/1778677...,Stripe,EUR,€,NaN,https://kodopeople.com,['merged-customer'],Spain,NaN,Granada,18016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,177867721,cus_514e79e5-a727-48cb-96ad-daa56f6aca0b,cus_PzNLrP3gZiXUek,Carla Fernandez Kessler,carla.fernandez@emburse.com,Cancelled,2024-04-25 09:28:15+00:00,ds_78983044-48ff-11ef-a3c9-aba08b7ca782,"['ds_ab518fb2-48ff-11ef-a6a7-c71cb5a83d1c', 'd...","['9678837704', '31471805157', 'cus_PzNLrP3gZiX...",NaN,ES,NaN,Sevilla,41002,NaN,NaN,0,0,https://dashboard.stripe.com/customers/cus_PzN...,https://app.chartmogul.com/#/customers/1778677...,Stripe,EUR,€,NaN,https://emburse.com,['merged-customer'],Spain,NaN,Sevilla,41002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,177867731,cus_381d58a9-601c-4ddc-a7ed-3a6e4fbc3ce9,cus_Q0pi1v2jIh62HZ,erica fernandez,erica.fernandez.hg@gmail.com,Cancelled,2024-04-29 06:50:35+00:00,ds_78983044-48ff-11ef-a3c9-aba08b7ca782,['ds_78983044-48ff-11ef-a3c9-aba08b7ca782'],['cus_Q0pi1v2jIh62HZ'],NaN,ES,NaN,madrid,28011,NaN,NaN,0,0,https://dashboard.stripe.com/customers/cus_Q0p...,https://app.chartmogul.com/#/customers/1778677...,Stripe,EUR,€,NaN,NaN,[],Spain,NaN,madrid,28011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,177867725,cus_c10652bc-b214-4079-8864-fe059d4cc0b4,cus_Q0z30MSpmp5jHX,Gisela Moreno,gismormel@gmail.com,Cancelled,2024-04-29 16:29:45+00:00,ds_78983044-48ff-11ef-a3c9-aba08b7ca782,['ds_78983044-48ff-11ef-a3c9-aba08b7ca782'],['cus_Q0z30MSpmp5jHX'],NaN,ES,NaN,Reus,43201,NaN,NaN,0,0,https://dashboard.stripe.com/customers/cus_Q0z...,https://app.chartmogul.com/#/customers/1778677...,Stripe,EUR,€,NaN,NaN,[],Spain,NaN,Reus,43201,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [349]:
df_CM_customers_clean['customer-since'].isna().sum()

np.int64(72)

In [350]:
df_HD_payments_clean.head(5)

,id,bankId,contactId,contactName,amount,desc,date,change,documentType,documentId
0,688375402f5c9baf800ce037,6697ee29ecc2d0d7aa0e0db4,66a0df36402cde9dc801b668,Slack Technologies Limited,-63.53,Compra SBIE-9184465 Fra. SBIE-9184465 Slack Te...,2025-07-25 00:00:00,NaN,trans,688374724c3f93c8740102cf
1,688360c3d27657ece0045357,6697e93c6fb022a948097230,NaN,NaN,1086.49,"TRANSFERENCIA DE STRIPE, CONCEPTO STRIPE.",2025-07-23 22:00:00,NaN,trans,68834aa38178673ac702d33b
2,688360c3d27657ece0045358,6697f010aa923f537703964e,NaN,NaN,-1086.49,"TRANSFERENCIA DE STRIPE, CONCEPTO STRIPE.",2025-07-23 22:00:00,NaN,entry,688360c3d27657ece0045356
3,68837548f95ef653730b4b50,6697ee29ecc2d0d7aa0e0db4,672ca6594cc0add3080b6460,Kaspr SAS,-87.50,Compra 257FA40F-0011 Fra. 257FA40F-0011 Kaspr SAS,2025-07-23 00:00:00,NaN,trans,688374724c3f93c8740102ce
4,688360c43545535aec094d0c,6697e93c6fb022a948097230,NaN,NaN,682.72,"TRANSFERENCIA DE STRIPE, CONCEPTO STRIPE.",2025-07-22 22:00:00,NaN,trans,6881f2d0d2b58941d004bf51

In [351]:
df_HD_invoices_clean.head(5)

,id,contact,contactName,desc,date,dueDate,multipledueDate,forecastDate,notes,tags,products,tax,subtotal,discount,total,language,status,customFields,docNumber,currency,currencyChange,paymentsDetail,paymentsTotal,paymentsPending,paymentsRefunds,shipping,paymentMethodId,multipledueDate.date,multipledueDate.amount
0,68640b2e4d4b9230af022ea8,6852bf0ed7f7b87ec2042a11,MediaEngine Srl,7BE139D9-5817,2025-06-29 22:00:00,NaN,[],NaN,NaN,[],"[{'name': '', 'desc': '', 'price': 99.83, 'uni...",0.00,99.83,0.0,99.83,es,1,[],F250383,eur,1,"[{'id': '6864fa8a1192b29d9d0c2745', 'amount': ...",99.83,0.0,0.0,NaN,NaN,NaN,NaN
1,68640b2e4d4b9230af022eb5,67ae2899d92c82a3ed0c50ad,Manum Training & Development S.L,7BE139D9-5820,2025-06-29 22:00:00,NaN,[],NaN,NaN,[],"[{'name': '', 'desc': '', 'price': 74.50413223...",15.65,74.50,0.0,90.15,es,1,[],F250384,eur,1,"[{'id': '6864fa85ba573f3f0e088f2c', 'amount': ...",90.15,0.0,0.0,NaN,NaN,NaN,NaN
2,68640b2e4d4b9230af022ec5,66e853461726c08ac9012017,Fever Labs Inc,7BE139D9-5824,2025-06-29 22:00:00,NaN,[],NaN,NaN,[],"[{'name': '', 'desc': '', 'price': 868.67, 'un...",0.00,868.67,0.0,868.67,es,1,[],F250385,eur,1,"[{'id': '6864fa822531707a9909d4f3', 'amount': ...",868.67,0.0,0.0,NaN,NaN,NaN,NaN
3,68640b2e4d4b9230af022ed2,67ec0bbb7669e0088a063e01,Oriol MaynÃ©s,7BE139D9-5834,2025-06-29 22:00:00,NaN,[],NaN,NaN,[],"[{'name': '', 'desc': '', 'price': 49, 'units'...",10.29,49.00,0.0,59.29,es,1,[],F250386,eur,1,"[{'id': '6864fa7f3842cb223003f776', 'amount': ...",59.29,0.0,0.0,NaN,NaN,NaN,NaN
4,68640b2f4d4b9230af022ee2,67ae2898d92c82a3ed0c5084,"4FOREVERYTHING, SL",7BE139D9-5841,2025-06-29 22:00:00,NaN,[],NaN,NaN,[],"[{'name': '', 'desc': '', 'price': 98, 'units'...",20.58,98.00,0.0,118.58,es,1,[],F250387,eur,1,"[{'id': '6864fa7db66170a2ea06d733', 'amount': ...",118.58,0.0,0.0,NaN,NaN,NaN,NaN

In [352]:
# Function to check how to map specific customer records between Chartmogul and Holded 
def check_column_match(df_cm, df_hd, cm_col, hd_col):
    """
    Check exact matches between a column in ChartMogul data 
    and a column in Holded data.
    
    Parameters:
        df_cm (pd.DataFrame): ChartMogul dataframe
        df_hd (pd.DataFrame): Holded dataframe
        cm_col (str): column name in ChartMogul dataframe
        hd_col (str): column name in Holded dataframe
    
    Returns:
        dict: match statistics
    """
    # Ensure columns exist
    if cm_col not in df_cm.columns:
        raise ValueError(f"Column '{cm_col}' not found in ChartMogul dataframe.")
    if hd_col not in df_hd.columns:
        raise ValueError(f"Column '{hd_col}' not found in Holded dataframe.")

    # Get unique, non-null values for comparison
    cm_values = set(df_cm[cm_col].dropna().astype(str).str.strip())
    hd_values = set(df_hd[hd_col].dropna().astype(str).str.strip())

    # Find matches
    matches = cm_values.intersection(hd_values)

    # Stats
    cm_total = len(cm_values)
    hd_total = len(hd_values)
    match_count = len(matches)

    stats = {
        "cm_unique_values": cm_total,
        "hd_unique_values": hd_total,
        "matches_found": match_count,
        "percent_of_cm_matched": match_count / cm_total * 100 if cm_total else 0,
        "percent_of_hd_matched": match_count / hd_total * 100 if hd_total else 0,
        "matched_values": matches
    }

    return stats

# Example usage:
# stats = check_column_match(df_CM_customers_clean, df_HD_invoices_clean, "external_id", "contact")
# print(stats)

In [353]:
# Run the match check
stats = check_column_match(
    df_CM_customers_clean,   # ChartMogul customers dataframe
    df_HD_invoices_clean,    # Holded invoices dataframe
    "external_id",           # Column from ChartMogul customers
    "contact"                # Column from Holded invoices
)

# Print the results
print(stats)

{'cm_unique_values': 200, 'hd_unique_values': 554, 'matches_found': 0, 'percent_of_cm_matched': 0.0, 'percent_of_hd_matched': 0.0, 'matched_values': set()}

In [354]:
import pandas as pd
from difflib import SequenceMatcher

def verify_customer_matching(df_cm_customers, df_hd_invoices, df_hd_contacts=None):
    results = {}

    # 1. Match by external_id ↔ contact
    matches_id = df_hd_invoices['contact'].isin(df_cm_customers['external_id'])
    results['id_match'] = matches_id.sum(), len(df_hd_invoices), matches_id.mean()

    # 2. Match by email (requires df_hd_contacts for Holded emails)
    if df_hd_contacts is not None and 'email' in df_hd_contacts.columns:
        df_hd_invoices_contacts = df_hd_invoices.merge(df_hd_contacts[['id', 'email']],
                                                       left_on='contact',
                                                       right_on='id',
                                                       how='left')
        matches_email = df_hd_invoices_contacts['email'].isin(df_cm_customers['email'])
        results['email_match'] = matches_email.sum(), len(df_hd_invoices_contacts), matches_email.mean()

    # 3. Match by VAT number (requires df_hd_contacts)
    if df_hd_contacts is not None and 'vatnumber' in df_hd_contacts.columns:
        df_hd_invoices_contacts = df_hd_invoices.merge(df_hd_contacts[['id', 'vatnumber']],
                                                       left_on='contact',
                                                       right_on='id',
                                                       how='left')
        if 'vatnumber' in df_cm_customers.columns:
            matches_vat = df_hd_invoices_contacts['vatnumber'].isin(df_cm_customers['vatnumber'])
            results['vat_match'] = matches_vat.sum(), len(df_hd_invoices_contacts), matches_vat.mean()

    # 4. Fuzzy match by company/contactName
    cm_names = df_cm_customers['company'].dropna().unique()
    hd_names = df_hd_invoices['contactName'].dropna().unique()

    fuzzy_matches = 0
    for hd_name in hd_names:
        for cm_name in cm_names:
            if SequenceMatcher(None, str(hd_name).lower(), str(cm_name).lower()).ratio() > 0.85:
                fuzzy_matches += 1
                break
    results['fuzzy_name_match'] = fuzzy_matches, len(hd_names), fuzzy_matches / len(hd_names)

    # Print results
    for method, (matches, total, ratio) in results.items():
        print(f"{method}: {matches}/{total} matches ({ratio:.2%})")

# Example usage:
# verify_customer_matching(df_CM_customers_clean, df_HD_invoices_clean, df_HD_contacts_clean)

In [355]:
verify_customer_matching(df_CM_customers_clean, df_HD_invoices_clean, df_HD_contacts_clean)

id_match: 0/1111 matches (0.00%)
email_match: 1066/1111 matches (95.95%)
fuzzy_name_match: 1/453 matches (0.22%)

EBITDA CALCULATION

In [356]:
df_HD_contacts_clean.head(1)

,id,customId,name,code,vatnumber,tradeName,email,mobile,phone,type,iban,swift,groupId,clientRecord,supplierRecord,billAddress,customFields,defaults,socialNetworks,tags,notes,contactPersons,shippingAddresses,isperson,createdAt,updatedAt,updatedHash
0,6694f45fc6f6db032502c35b,5863162.0,Framer B.V.,NL853695386B01,NL853695386B01,Framer B.V.,NaN,NaN,NaN,supplier,NaN,NaN,NaN,0,"{""num"": 40000001, ""name"": ""Framer B.V.""}","{""address"": null, ""city"": null, ""postalCode"": ...",[],"{""salesChannel"": 0, ""expensesAccount"": ""6694dc...","{""facebook"": """", ""twitter"": """", ""website"": """"}","[""opex"", ""prod"", ""tool""]",[],[],[],0,1721037919,1752252967,3704e8a63e113125690c97079e41acc8

In [357]:
df_HD_contacts_clean['type'].value_counts()

type
supplier    84
client      71
0            3
Name: count, dtype: int64

In [358]:
df_HD_contacts_clean['type'].isna().sum()

np.int64(342)

In [359]:
df_HD_contacts_clean['tags'].value_counts()

tags
[]                                         416
["cogs", "tech", "tool"]                    15
["opex", "leg", "vendor"]                    9
["opex", "hr", "vendor"]                     9
["cac", "sale", "vendor"]                    6
["opex", "prod", "tool"]                     5
["opex", "fin", "vendor"]                    5
["opex", "tech", "staffing"]                 5
["opex", "fin", "tool"]                      4
["cac", "mkg", "vendor"]                     3
["opex", "tech", "vendor"]                   3
["opex", "ops", "vendor"]                    3
["opex", "ops", "tool"]                      3
["opex", "mkg", "tool"]                      2
["cac", "sale", "tool"]                      2
["cac", "sale", "staffing"]                  2
["opex", "ops", "staffing"]                  1
["opex", "prod", "staffing"]                 1
["opex", "tech", "tool"]                     1
["opex", "sale", "tool"]                     1
["cac", "mkg", "tool"]                       1
["cogs", "tech", "vendor"]                   1
["sales", "vendor", "cac"]                   1
["costes financieros", "fin", "vendor"]      1
Name: count, dtype: int64

CAC CALCULATION

In [360]:
# Verify that the IDs used in CAC calculation align between df_HD_purchases_clean and df_HD_contacts_clean

# 1. Get unique contact IDs from purchases
purchase_contact_ids = set(df_HD_purchases_clean['contact'].dropna().unique())

# 2. Get unique IDs from contacts
contact_ids = set(df_HD_contacts_clean['id'].dropna().unique())

# 3. Intersection and differences
matching_ids = purchase_contact_ids & contact_ids
missing_in_contacts = purchase_contact_ids - contact_ids
missing_in_purchases = contact_ids - purchase_contact_ids

print(f"Total unique IDs in purchases: {len(purchase_contact_ids)}")
print(f"Total unique IDs in contacts: {len(contact_ids)}")
print(f"Matching IDs: {len(matching_ids)}")
print(f"IDs in purchases but not in contacts: {len(missing_in_contacts)}")
print(f"IDs in contacts but not in purchases: {len(missing_in_purchases)}")

# Optional: Inspect the mismatches
if missing_in_contacts:
    print("\nSample IDs in purchases but not in contacts:")
    print(list(missing_in_contacts)[:10])

if missing_in_purchases:
    print("\nSample IDs in contacts but not in purchases:")
    print(list(missing_in_purchases)[:10])

Total unique IDs in purchases: 86
Total unique IDs in contacts: 500
Matching IDs: 82
IDs in purchases but not in contacts: 4
IDs in contacts but not in purchases: 418

Sample IDs in purchases but not in contacts:
['686f9d2da3972b9b98032aff', '6863a12953a0884bee0b4854', '686804f1fcb248d793050243', '6694f3fb49a286777c0c6836']

Sample IDs in contacts but not in purchases:
['67064c9c873b2f8c560b6b56', '67211488581d8fa5ba00de5a', '6721149c68c118020103ba16', '670645e1cb48b8010906f6a5', '673f6f5d8209cbfb00057ae3', '6721146332b39c15d7060858', '6721148a581d8fa5ba00dea8', '6721148d581d8fa5ba00df03', '673f6f955c6cca21e409bb95', '6721147a86950846bd0a680d']

In [361]:
# List of purchase contact IDs that are not found in contacts
missing_in_contacts_ids = [
    '686f9d2da3972b9b98032aff',
    '6863a12953a0884bee0b4854',
    '686804f1fcb248d793050243',
    '6694f3fb49a286777c0c6836'
]

# Filter purchases for those IDs
df_missing_purchases = df_HD_purchases_clean[
    df_HD_purchases_clean['contact'].isin(missing_in_contacts_ids)
]

df_missing_purchases

,id,contact,contactName,desc,date,dueDate,multipledueDate,forecastDate,notes,tags,products,tax,subtotal,discount,total,language,status,customFields,docNumber,currency,currencyChange,paymentsTotal,paymentsPending,paymentsRefunds,paymentsDetail,multipledueDate.date,multipledueDate.amount,from.id,from.docType
22,686f9d91ac4a87122c029343,686f9d2da3972b9b98032aff,CloudTalk S. Γ. O. (CloudTalk S. Γ. O.),Fra. 25014245 CloudTalk S. Γ. O.,2025-07-07 22:00:00,NaN,[],NaN,NaN,[],"[{'name': 'Fra. 25014245 CloudTalk S. Γ. O.', ...",0.00,17.04,0,17.04,NaN,1,[],25014245,usd,1.173489,17.04,0.0,0,"[{'id': '68836542313f10285c00fad1', 'amount': ...",NaN,NaN,NaN,NaN
30,68680506905fa42e4a054195,686804f1fcb248d793050243,"NO MORE UPDATES, S.L (NO MORE UPDATES, S.L)","Fra. nº: 2 NO MORE UPDATES, S.L",2025-06-29 22:00:00,NaN,[],NaN,NaN,[],"[{'name': 'Fra. nº: 2 NO MORE UPDATES, S.L', '...",57.71,274.80,0,332.51,es,1,[],nº: 2,eur,1.000000,332.51,0.0,0,"[{'id': '6883608b0d7f517b30055105', 'amount': ...",NaN,NaN,NaN,NaN
36,6863a15d0822490fef02b4d5,6863a12953a0884bee0b4854,D'ELIA ABRAMO (D'ELIA ABRAMO),Fra. 07 D'ELIA ABRAMO,2025-06-25 22:00:00,NaN,[],NaN,NaN,[],"[{'name': ""Fra. 07 D'ELIA ABRAMO"", 'desc': ""Fr...",0.00,350.00,0,350.00,es,1,[],07,eur,1.000000,350.00,0.0,0,"[{'id': '6863f0b5b77c31cd56097323', 'amount': ...",NaN,NaN,NaN,NaN
271,6751c073f643b32480059974,6694f3fb49a286777c0c6836,"NUCLIO DIGITAL PLUS, S.L. (NUCLIO DIGITAL PLUS...","Fra. 24453 NUCLIO DIGITAL PLUS, S.L.",2024-12-02 23:00:00,NaN,[],NaN,NaN,[],"[{'name': 'Fra. 24453 NUCLIO DIGITAL PLUS, S.L...",210.00,1000.00,0,1210.00,es,1,[],24453,eur,1.000000,1210.00,0.0,0,"[{'id': '6773d63cb0d3b8d7bf0ca605', 'amount': ...",NaN,NaN,NaN,NaN
278,67502ec5d411f625340fcf66,6694f3fb49a286777c0c6836,"NUCLIO DIGITAL PLUS, S.L. (NUCLIO DIGITAL PLUS...","Fra. 24435 NUCLIO DIGITAL PLUS, S.L.",2024-11-29 23:00:00,NaN,[],NaN,NaN,[],"[{'name': 'Fra. 24435 NUCLIO DIGITAL PLUS, S.L...",16.80,80.00,0,96.80,es,1,[],24435,eur,1.000000,96.80,0.0,0,"[{'id': '67c36a7d859961d1700f6b17', 'amount': ...",NaN,NaN,NaN,NaN
306,67334fcba9ac4db815077f11,6694f3fb49a286777c0c6836,"NUCLIO DIGITAL PLUS, S.L. (NUCLIO DIGITAL PLUS...","Fra. 24419 NUCLIO DIGITAL PLUS, S.L.",2024-11-03 23:00:00,NaN,[],NaN,NaN,[],"[{'name': 'Fra. 24419 NUCLIO DIGITAL PLUS, S.L...",210.00,1000.00,0,1210.00,es,1,[],24419,eur,1.000000,1210.00,0.0,0,"[{'id': '674969a07129fff3b7062d88', 'amount': ...",NaN,NaN,NaN,NaN
338,670452d186d63c1f2e0b7907,6694f3fb49a286777c0c6836,"NUCLIO DIGITAL PLUS, S.L. (NUCLIO DIGITAL PLUS...","Fra. 24380 NUCLIO DIGITAL PLUS, S.L.",2024-09-30 22:00:00,NaN,[],NaN,NaN,[],"[{'name': 'Fra. 24380 NUCLIO DIGITAL PLUS, S.L...",210.00,1000.00,0,1210.00,es,1,[],24380,eur,1.000000,1210.00,0.0,0,"[{'id': '672b9ad23ff8c7b6560e3403', 'amount': ...",NaN,NaN,NaN,NaN
345,670452f5a2ba8801cd0287fb,6694f3fb49a286777c0c6836,"NUCLIO DIGITAL PLUS, S.L. (NUCLIO DIGITAL PLUS...","Fra. 24360 NUCLIO DIGITAL PLUS, S.L.",2024-09-29 22:00:00,NaN,[],NaN,NaN,[],"[{'name': 'Fra. 24360 NUCLIO DIGITAL PLUS, S.L...",184.80,880.00,0,1064.80,es,1,[],24360,eur,1.000000,1064.80,0.0,0,"[{'id': '67c36a7d8490e92bac09b67b', 'amount': ...",NaN,NaN,NaN,NaN
404,66a0dea37bee72d5b1041ca3,6694f3fb49a286777c0c6836,"NUCLIO DIGITAL PLUS, S.L. (NUCLIO DIGITAL PLUS...","Fra. 24260 NUCLIO DIGITAL PLUS, S.L.",2024-06-30 22:00:00,NaN,[],NaN,NaN,[],"[{'name': 'Fra. 24260 NUCLIO DIGITAL PLUS, S.L...",210.00,1000.00,0,1210.00,es,1,[],24260,eur,1.000000,1210.00,0.0,0,"[{'id': '66a0f02f2cbdd742c4089266', 'amount': ...",NaN,NaN,NaN,NaN
412,66a0e92f0ab9c8e194087598,6694f3fb49a286777c0c6836,"NUCLIO DIGITAL PLUS, S.L. (NUCLIO DIGITAL PLUS...","Fra. 24210 NUCLIO DIGITAL PLUS, S.L.",2024-06-30 22:00:00,NaN,[],NaN,NaN,[],"[{'name': 'Fra. 24210 NUCLIO DIGITAL PLUS, S.L...",420.00,2000.00,0,2420.00,es,1,[],24210,eur,1.000000,2420.00,0.0,0,"[{'id': '66a0efb6d6a0bdb3480f2ef8', 'amount': ...",NaN,NaN,NaN,NaN
418,66a5f9eebca7cd8b3a0bb399,6694f3fb49a286777c0c6836,"NUCLIO DIGITAL PLUS, S.L. (NUCLIO DIGITAL PLUS...",NaN,2024-06-30 22:00:00,NaN,[],NaN,NaN,[],"[{'name': '', 'desc': '', 'price': 600, 'units...",126.00,600.00,0,726.00,NaN,1,[],24232,eur,1.000000,726.00,0.0,0,"[{'id': '66a5faf69a11e7594c082fbd', 'amount': ...",NaN,NaN,NaN,NaN
420,66b0b9e34faec4c3130d80fc,6694f3fb49a286777c0c6836,"NUCLIO DIGITAL PLUS, S.L. (NUCLIO DIGITAL PLUS...","Fra. 24163 NUCLIO DIGITAL PLUS, S.L.",2024-06-30 22:00:00,NaN,[],NaN,NaN,[],"[{'name': 'Fra. 24163 NUCLIO DIGITAL PLUS, S.L...",420.00,2000.00,0,2420.00,es,1,[],24163,eur,1.000000,2420.00,0.0,0,"[{'id': '66e077100d0355348e069b70', 'amount': ...",NaN,NaN,NaN,NaN
421,66b0ba0fd219b7cf8f0f6653,6694f3fb49a286777c0c6836,"NUCLIO DIGITAL PLUS, S.L. (NUCLIO DIGITAL PLUS...","Fra. 24101 NUCLIO DIGITAL PLUS, S.L.",2024-06-30 22:00:00,NaN,[],NaN,NaN,[],"[{'name': 'Fra. 24101 NUCLIO DIGITAL PLUS, S.L...",420.00,2000.00,0,2420.00,es,1,[],24101,eur,1.000000,2420.00,0.0,0,"[{'id': '66e07710f703ed0c780fd953', 'amount': ...",NaN,NaN,NaN,NaN
422,66b0ba396d006b2609066afd,6694f3fb49a286777c0c6836,"NUCLIO DIGITAL PLUS, S.L. (NUCLIO DIGITAL PLUS...","Fra. 24086 NUCLIO DIGITAL PLUS, S.L.",2024-06-30 22:00:00,NaN,[],NaN,NaN,[],"[{'name': 'Fra. 24086 NUCLIO DIGITAL PLUS, S.L...",71.40,340.00,0,411.40,es,1,[],24086,eur,1.000000,411.40,0.0,0,"[{'id': '66e07711686fe150a20fb219', 'amount': ...",NaN,NaN,NaN,NaN
423,66b0ba64147d6701fa0170db,6694f3fb49a286777c0c6836,"NUCLIO DIGITAL PLUS, S.L. (NUCLIO DIGITAL PLUS...","Fra. 24059 NUCLIO DIGITAL PLUS, S.L.",2024-06-30 22:00:00,NaN,[],NaN,NaN,[],"[{'name': 'Fra. 24059 NUCLIO DIGITAL PLUS, S.L...",25.20,120.00,0,145.20,es,1,[],24059,eur,1.000000,145.20,0.0,0,"[{'id': '66e077117bb8086f7f0035b0', 'amount': ...",NaN,NaN,NaN,NaN
427,66e7f6316161fce331040a7c,6694f3fb49a286777c0c6836,"NUCLIO DIGITAL PLUS, S.L. (NUCLIO DIGITAL PLUS...","Fra. #F240175 NUCLIO DIGITAL PLUS, S.L.",2024-06-30 22:00:00,NaN,[],NaN,NaN,[],"[{'name': 'Fra. #F240175 NUCLIO DIGITAL PLUS, ...",393.75,1875.00,0,2268.75,es,1,[],#F240175,eur,1.000000,2268.75,0.0,0,"[{'id': '66e7f651c08e679d40033a39', 'amount': ...",NaN,NaN,NaN,NaN
428,669500961dc63a7428034c2a,6694f3fb49a286777c0c6836,"NUCLIO DIGITAL PLUS, S.L. (NUCLIO DIGITAL PLUS...","Fra. 24232 NUCLIO DIGITAL PLUS, S.L.",2024-06-29 22:00:00,NaN,[],NaN,NaN,[],"[{'name': 'Fra. 24232 NUCLIO DIGITAL PLUS, S.L...",50.40,240.00,0,290.40,NaN,1,[],#24232,eur,1.000000,290.40,0.0,0,"[{'id': '66a5fcd388e00e5e5c01eeb1', 'amount': ...",NaN,NaN,NaN,NaN
435,669500aab2d5204334069ac4,6694f3fb49a286777c0c6836,"NUCLIO DIGITAL PLUS, S.L. (NUCLIO DIGITAL PLUS...","Fra. 24183 NUCLIO DIGITAL PLUS, S.L.",2024-05-30 22:00:00,NaN,[],NaN,NaN,[],"[{'name': 'Fra. 24183 NUCLIO DIGITAL PLUS, S.L...",50.40,240.00,0,290.40,es,1,[],24183,eur,1.000000,290.40,0.0,0,"[{'id': '66b0be228c928c42350fdca0', 'amount': ...",NaN,NaN,NaN,NaN
440,669500a88445d9650904d6a2,6694f3fb49a286777c0c6836,"NUCLIO DIGITAL PLUS, S.L. (NUCLIO DIGITAL PLUS...","Fra. 24132 NUCLIO DIGITAL PLUS, S.L.",2024-04-29 22:00:00,NaN,[],NaN,NaN,[],"[{'name': 'Fra. 24132 NUCLIO DIGITAL PLUS, S.L...",161.28,768.00,0,929.28,es,1,[],24132,eur,1.000000,929.28,0.0,0,"[{'id': '669e671a72d835510c0669cc', 'amount': ...",NaN,NaN,NaN,NaN

In [362]:
df_HD_contacts_clean[(df_HD_contacts_clean['tags'] != "[]") & (df_HD_contacts_clean['type'] == "client")]

Empty DataFrame
Columns: [id, customId, name, code, vatnumber, tradeName, email, mobile, phone, type, iban, swift, groupId, clientRecord, supplierRecord, billAddress, customFields, defaults, socialNetworks, tags, notes, contactPersons, shippingAddresses, isperson, createdAt, updatedAt, updatedHash]
Index: []

In [363]:
df_CM_customers_clean.head(1)

,id,uuid,external_id,name,email,status,customer-since,data_source_uuid,data_source_uuids,external_ids,company,country,state,city,zip,lead_created_at,free_trial_started_at,mrr,arr,billing-system-url,chartmogul-url,billing-system-type,currency,currency-sign,owner,website_url,attributes.tags,address.country,address.state,address.city,address.address_zip,attributes.hubspot.Company_owner,attributes.hubspot.Lifecycle_Stage,attributes.hubspot.Latest_Source,attributes.hubspot.Original_Source,attributes.stripe.userId,attributes.stripe.companyId,attributes.hubspot.Industry,attributes.hubspot.Time_Last_Seen,attributes.hubspot.Type
0,177867729,cus_9a55ecba-bcdc-4d19-89d1-05ddfac08906,cus_PubGEWYD0zJS7r,Edicom Capital,lgalceran@edicom.es,Active,2024-04-12 15:30:48+00:00,ds_78983044-48ff-11ef-a3c9-aba08b7ca782,['ds_78983044-48ff-11ef-a3c9-aba08b7ca782'],['cus_PubGEWYD0zJS7r'],NaN,ES,NaN,Paterna,46980,NaN,NaN,30135,361620,https://dashboard.stripe.com/customers/cus_Pub...,https://app.chartmogul.com/#/customers/1778677...,Stripe,EUR,€,NaN,https://edicom.es,[],Spain,NaN,Paterna,46980,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN